package com.ht.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PCBAInventoryExample1 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DL_PCBAInventory
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DL_PCBAInventory
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DL_PCBAInventory
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAInventory
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public PCBAInventoryExample1() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAInventory
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAInventory
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAInventory
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAInventory
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAInventory
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAInventory
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAInventory
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAInventory
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAInventory
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAInventory
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DL_PCBAInventory
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIDIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIDIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIDEqualTo(String value) {
            addCriterion("ID =", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotEqualTo(String value) {
            addCriterion("ID <>", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThan(String value) {
            addCriterion("ID >", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThan(String value) {
            addCriterion("ID <", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDLike(String value) {
            addCriterion("ID like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotLike(String value) {
            addCriterion("ID not like", value, "ID");
            return (Criteria) this;
        }

        public Criteria andIDIn(List<String> values) {
            addCriterion("ID in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotIn(List<String> values) {
            addCriterion("ID not in", values, "ID");
            return (Criteria) this;
        }

        public Criteria andIDBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andIDNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "ID");
            return (Criteria) this;
        }

        public Criteria andWOIsNull() {
            addCriterion("WO is null");
            return (Criteria) this;
        }

        public Criteria andWOIsNotNull() {
            addCriterion("WO is not null");
            return (Criteria) this;
        }

        public Criteria andWOEqualTo(String value) {
            addCriterion("WO =", value, "WO");
            return (Criteria) this;
        }

        public Criteria andWONotEqualTo(String value) {
            addCriterion("WO <>", value, "WO");
            return (Criteria) this;
        }

        public Criteria andWOGreaterThan(String value) {
            addCriterion("WO >", value, "WO");
            return (Criteria) this;
        }

        public Criteria andWOGreaterThanOrEqualTo(String value) {
            addCriterion("WO >=", value, "WO");
            return (Criteria) this;
        }

        public Criteria andWOLessThan(String value) {
            addCriterion("WO <", value, "WO");
            return (Criteria) this;
        }

        public Criteria andWOLessThanOrEqualTo(String value) {
            addCriterion("WO <=", value, "WO");
            return (Criteria) this;
        }

        public Criteria andWOLike(String value) {
            addCriterion("WO like", value, "WO");
            return (Criteria) this;
        }

        public Criteria andWONotLike(String value) {
            addCriterion("WO not like", value, "WO");
            return (Criteria) this;
        }

        public Criteria andWOIn(List<String> values) {
            addCriterion("WO in", values, "WO");
            return (Criteria) this;
        }

        public Criteria andWONotIn(List<String> values) {
            addCriterion("WO not in", values, "WO");
            return (Criteria) this;
        }

        public Criteria andWOBetween(String value1, String value2) {
            addCriterion("WO between", value1, value2, "WO");
            return (Criteria) this;
        }

        public Criteria andWONotBetween(String value1, String value2) {
            addCriterion("WO not between", value1, value2, "WO");
            return (Criteria) this;
        }

        public Criteria andWOQuantityIsNull() {
            addCriterion("WOQuantity is null");
            return (Criteria) this;
        }

        public Criteria andWOQuantityIsNotNull() {
            addCriterion("WOQuantity is not null");
            return (Criteria) this;
        }

        public Criteria andWOQuantityEqualTo(Double value) {
            addCriterion("WOQuantity =", value, "WOQuantity");
            return (Criteria) this;
        }

        public Criteria andWOQuantityNotEqualTo(Double value) {
            addCriterion("WOQuantity <>", value, "WOQuantity");
            return (Criteria) this;
        }

        public Criteria andWOQuantityGreaterThan(Double value) {
            addCriterion("WOQuantity >", value, "WOQuantity");
            return (Criteria) this;
        }

        public Criteria andWOQuantityGreaterThanOrEqualTo(Double value) {
            addCriterion("WOQuantity >=", value, "WOQuantity");
            return (Criteria) this;
        }

        public Criteria andWOQuantityLessThan(Double value) {
            addCriterion("WOQuantity <", value, "WOQuantity");
            return (Criteria) this;
        }

        public Criteria andWOQuantityLessThanOrEqualTo(Double value) {
            addCriterion("WOQuantity <=", value, "WOQuantity");
            return (Criteria) this;
        }

        public Criteria andWOQuantityIn(List<Double> values) {
            addCriterion("WOQuantity in", values, "WOQuantity");
            return (Criteria) this;
        }

        public Criteria andWOQuantityNotIn(List<Double> values) {
            addCriterion("WOQuantity not in", values, "WOQuantity");
            return (Criteria) this;
        }

        public Criteria andWOQuantityBetween(Double value1, Double value2) {
            addCriterion("WOQuantity between", value1, value2, "WOQuantity");
            return (Criteria) this;
        }

        public Criteria andWOQuantityNotBetween(Double value1, Double value2) {
            addCriterion("WOQuantity not between", value1, value2, "WOQuantity");
            return (Criteria) this;
        }

        public Criteria andUIDIsNull() {
            addCriterion("UID is null");
            return (Criteria) this;
        }

        public Criteria andUIDIsNotNull() {
            addCriterion("UID is not null");
            return (Criteria) this;
        }

        public Criteria andUIDEqualTo(String value) {
            addCriterion("UID =", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDNotEqualTo(String value) {
            addCriterion("UID <>", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDGreaterThan(String value) {
            addCriterion("UID >", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDGreaterThanOrEqualTo(String value) {
            addCriterion("UID >=", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDLessThan(String value) {
            addCriterion("UID <", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDLessThanOrEqualTo(String value) {
            addCriterion("UID <=", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDLike(String value) {
            addCriterion("UID like", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDNotLike(String value) {
            addCriterion("UID not like", value, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDIn(List<String> values) {
            addCriterion("UID in", values, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDNotIn(List<String> values) {
            addCriterion("UID not in", values, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDBetween(String value1, String value2) {
            addCriterion("UID between", value1, value2, "UID");
            return (Criteria) this;
        }

        public Criteria andUIDNotBetween(String value1, String value2) {
            addCriterion("UID not between", value1, value2, "UID");
            return (Criteria) this;
        }

        public Criteria andPartNumberIsNull() {
            addCriterion("PartNumber is null");
            return (Criteria) this;
        }

        public Criteria andPartNumberIsNotNull() {
            addCriterion("PartNumber is not null");
            return (Criteria) this;
        }

        public Criteria andPartNumberEqualTo(String value) {
            addCriterion("PartNumber =", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberNotEqualTo(String value) {
            addCriterion("PartNumber <>", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberGreaterThan(String value) {
            addCriterion("PartNumber >", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberGreaterThanOrEqualTo(String value) {
            addCriterion("PartNumber >=", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberLessThan(String value) {
            addCriterion("PartNumber <", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberLessThanOrEqualTo(String value) {
            addCriterion("PartNumber <=", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberLike(String value) {
            addCriterion("PartNumber like", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberNotLike(String value) {
            addCriterion("PartNumber not like", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberIn(List<String> values) {
            addCriterion("PartNumber in", values, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberNotIn(List<String> values) {
            addCriterion("PartNumber not in", values, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberBetween(String value1, String value2) {
            addCriterion("PartNumber between", value1, value2, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberNotBetween(String value1, String value2) {
            addCriterion("PartNumber not between", value1, value2, "partNumber");
            return (Criteria) this;
        }

        public Criteria andFactoryIsNull() {
            addCriterion("Factory is null");
            return (Criteria) this;
        }

        public Criteria andFactoryIsNotNull() {
            addCriterion("Factory is not null");
            return (Criteria) this;
        }

        public Criteria andFactoryEqualTo(String value) {
            addCriterion("Factory =", value, "factory");
            return (Criteria) this;
        }

        public Criteria andFactoryNotEqualTo(String value) {
            addCriterion("Factory <>", value, "factory");
            return (Criteria) this;
        }

        public Criteria andFactoryGreaterThan(String value) {
            addCriterion("Factory >", value, "factory");
            return (Criteria) this;
        }

        public Criteria andFactoryGreaterThanOrEqualTo(String value) {
            addCriterion("Factory >=", value, "factory");
            return (Criteria) this;
        }

        public Criteria andFactoryLessThan(String value) {
            addCriterion("Factory <", value, "factory");
            return (Criteria) this;
        }

        public Criteria andFactoryLessThanOrEqualTo(String value) {
            addCriterion("Factory <=", value, "factory");
            return (Criteria) this;
        }

        public Criteria andFactoryLike(String value) {
            addCriterion("Factory like", value, "factory");
            return (Criteria) this;
        }

        public Criteria andFactoryNotLike(String value) {
            addCriterion("Factory not like", value, "factory");
            return (Criteria) this;
        }

        public Criteria andFactoryIn(List<String> values) {
            addCriterion("Factory in", values, "factory");
            return (Criteria) this;
        }

        public Criteria andFactoryNotIn(List<String> values) {
            addCriterion("Factory not in", values, "factory");
            return (Criteria) this;
        }

        public Criteria andFactoryBetween(String value1, String value2) {
            addCriterion("Factory between", value1, value2, "factory");
            return (Criteria) this;
        }

        public Criteria andFactoryNotBetween(String value1, String value2) {
            addCriterion("Factory not between", value1, value2, "factory");
            return (Criteria) this;
        }

        public Criteria andLocationIsNull() {
            addCriterion("Location is null");
            return (Criteria) this;
        }

        public Criteria andLocationIsNotNull() {
            addCriterion("Location is not null");
            return (Criteria) this;
        }

        public Criteria andLocationEqualTo(String value) {
            addCriterion("Location =", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotEqualTo(String value) {
            addCriterion("Location <>", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThan(String value) {
            addCriterion("Location >", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationGreaterThanOrEqualTo(String value) {
            addCriterion("Location >=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThan(String value) {
            addCriterion("Location <", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLessThanOrEqualTo(String value) {
            addCriterion("Location <=", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationLike(String value) {
            addCriterion("Location like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotLike(String value) {
            addCriterion("Location not like", value, "location");
            return (Criteria) this;
        }

        public Criteria andLocationIn(List<String> values) {
            addCriterion("Location in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotIn(List<String> values) {
            addCriterion("Location not in", values, "location");
            return (Criteria) this;
        }

        public Criteria andLocationBetween(String value1, String value2) {
            addCriterion("Location between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andLocationNotBetween(String value1, String value2) {
            addCriterion("Location not between", value1, value2, "location");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("State is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("State is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("State =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("State <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("State >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("State >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("State <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("State <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("State in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("State not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("State between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("State not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andAvailableQuantityIsNull() {
            addCriterion("AvailableQuantity is null");
            return (Criteria) this;
        }

        public Criteria andAvailableQuantityIsNotNull() {
            addCriterion("AvailableQuantity is not null");
            return (Criteria) this;
        }

        public Criteria andAvailableQuantityEqualTo(Double value) {
            addCriterion("AvailableQuantity =", value, "availableQuantity");
            return (Criteria) this;
        }

        public Criteria andAvailableQuantityNotEqualTo(Double value) {
            addCriterion("AvailableQuantity <>", value, "availableQuantity");
            return (Criteria) this;
        }

        public Criteria andAvailableQuantityGreaterThan(Double value) {
            addCriterion("AvailableQuantity >", value, "availableQuantity");
            return (Criteria) this;
        }

        public Criteria andAvailableQuantityGreaterThanOrEqualTo(Double value) {
            addCriterion("AvailableQuantity >=", value, "availableQuantity");
            return (Criteria) this;
        }

        public Criteria andAvailableQuantityLessThan(Double value) {
            addCriterion("AvailableQuantity <", value, "availableQuantity");
            return (Criteria) this;
        }

        public Criteria andAvailableQuantityLessThanOrEqualTo(Double value) {
            addCriterion("AvailableQuantity <=", value, "availableQuantity");
            return (Criteria) this;
        }

        public Criteria andAvailableQuantityIn(List<Double> values) {
            addCriterion("AvailableQuantity in", values, "availableQuantity");
            return (Criteria) this;
        }

        public Criteria andAvailableQuantityNotIn(List<Double> values) {
            addCriterion("AvailableQuantity not in", values, "availableQuantity");
            return (Criteria) this;
        }

        public Criteria andAvailableQuantityBetween(Double value1, Double value2) {
            addCriterion("AvailableQuantity between", value1, value2, "availableQuantity");
            return (Criteria) this;
        }

        public Criteria andAvailableQuantityNotBetween(Double value1, Double value2) {
            addCriterion("AvailableQuantity not between", value1, value2, "availableQuantity");
            return (Criteria) this;
        }

        public Criteria andAvailableBatchIsNull() {
            addCriterion("AvailableBatch is null");
            return (Criteria) this;
        }

        public Criteria andAvailableBatchIsNotNull() {
            addCriterion("AvailableBatch is not null");
            return (Criteria) this;
        }

        public Criteria andAvailableBatchEqualTo(String value) {
            addCriterion("AvailableBatch =", value, "availableBatch");
            return (Criteria) this;
        }

        public Criteria andAvailableBatchNotEqualTo(String value) {
            addCriterion("AvailableBatch <>", value, "availableBatch");
            return (Criteria) this;
        }

        public Criteria andAvailableBatchGreaterThan(String value) {
            addCriterion("AvailableBatch >", value, "availableBatch");
            return (Criteria) this;
        }

        public Criteria andAvailableBatchGreaterThanOrEqualTo(String value) {
            addCriterion("AvailableBatch >=", value, "availableBatch");
            return (Criteria) this;
        }

        public Criteria andAvailableBatchLessThan(String value) {
            addCriterion("AvailableBatch <", value, "availableBatch");
            return (Criteria) this;
        }

        public Criteria andAvailableBatchLessThanOrEqualTo(String value) {
            addCriterion("AvailableBatch <=", value, "availableBatch");
            return (Criteria) this;
        }

        public Criteria andAvailableBatchLike(String value) {
            addCriterion("AvailableBatch like", value, "availableBatch");
            return (Criteria) this;
        }

        public Criteria andAvailableBatchNotLike(String value) {
            addCriterion("AvailableBatch not like", value, "availableBatch");
            return (Criteria) this;
        }

        public Criteria andAvailableBatchIn(List<String> values) {
            addCriterion("AvailableBatch in", values, "availableBatch");
            return (Criteria) this;
        }

        public Criteria andAvailableBatchNotIn(List<String> values) {
            addCriterion("AvailableBatch not in", values, "availableBatch");
            return (Criteria) this;
        }

        public Criteria andAvailableBatchBetween(String value1, String value2) {
            addCriterion("AvailableBatch between", value1, value2, "availableBatch");
            return (Criteria) this;
        }

        public Criteria andAvailableBatchNotBetween(String value1, String value2) {
            addCriterion("AvailableBatch not between", value1, value2, "availableBatch");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CreateUser is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CreateUser is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("CreateUser =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("CreateUser <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("CreateUser >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("CreateUser >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("CreateUser <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("CreateUser <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("CreateUser like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("CreateUser not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("CreateUser in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("CreateUser not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("CreateUser between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("CreateUser not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CreateTime is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CreateTime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CreateTime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CreateTime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CreateTime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CreateTime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CreateTime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CreateTime in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CreateTime not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CreateTime between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CreateTime not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andWorkCenterIsNull() {
            addCriterion("workcenter is null");
            return (Criteria) this;
        }

        public Criteria andWorkCenterIsNotNull() {
            addCriterion("workcenter is not null");
            return (Criteria) this;
        }

        public Criteria andWorkCenterEqualTo(String value) {
            addCriterion("workcenter =", value, "workCenter");
            return (Criteria) this;
        }

        public Criteria andWorkCenterNotEqualTo(String value) {
            addCriterion("workcenter <>", value, "workCenter");
            return (Criteria) this;
        }

        public Criteria andWorkCenterGreaterThan(String value) {
            addCriterion("workcenter >", value, "workCenter");
            return (Criteria) this;
        }

        public Criteria andWorkCenterGreaterThanOrEqualTo(String value) {
            addCriterion("workcenter >=", value, "workCenter");
            return (Criteria) this;
        }

        public Criteria andWorkCenterLessThan(String value) {
            addCriterion("workcenter <", value, "workCenter");
            return (Criteria) this;
        }

        public Criteria andWorkCenterLessThanOrEqualTo(String value) {
            addCriterion("workcenter <=", value, "workCenter");
            return (Criteria) this;
        }

        public Criteria andWorkCenterLike(String value) {
            addCriterion("workcenter like", value, "workCenter");
            return (Criteria) this;
        }

        public Criteria andWorkCenterNotLike(String value) {
            addCriterion("workcenter not like", value, "workCenter");
            return (Criteria) this;
        }

        public Criteria andWorkCenterIn(List<String> values) {
            addCriterion("workcenter in", values, "workCenter");
            return (Criteria) this;
        }

        public Criteria andWorkCenterNotIn(List<String> values) {
            addCriterion("workcenter not in", values, "workCenter");
            return (Criteria) this;
        }

        public Criteria andWorkCenterBetween(String value1, String value2) {
            addCriterion("workcenter between", value1, value2, "workCenter");
            return (Criteria) this;
        }

        public Criteria andWorkCenterNotBetween(String value1, String value2) {
            addCriterion("workcenter not between", value1, value2, "workCenter");
            return (Criteria) this;
        }

        public Criteria andStatus313IsNull() {
            addCriterion("313_Status is null");
            return (Criteria) this;
        }

        public Criteria andStatus313IsNotNull() {
            addCriterion("313_Status is not null");
            return (Criteria) this;
        }

        public Criteria andStatus313EqualTo(String value) {
            addCriterion("313_Status =", value, "status313");
            return (Criteria) this;
        }

        public Criteria andStatus313NotEqualTo(String value) {
            addCriterion("313_Status <>", value, "status313");
            return (Criteria) this;
        }

        public Criteria andStatus313GreaterThan(String value) {
            addCriterion("313_Status >", value, "status313");
            return (Criteria) this;
        }

        public Criteria andStatus313GreaterThanOrEqualTo(String value) {
            addCriterion("313_Status >=", value, "status313");
            return (Criteria) this;
        }

        public Criteria andStatus313LessThan(String value) {
            addCriterion("313_Status <", value, "status313");
            return (Criteria) this;
        }

        public Criteria andStatus313LessThanOrEqualTo(String value) {
            addCriterion("313_Status <=", value, "status313");
            return (Criteria) this;
        }

        public Criteria andStatus313Like(String value) {
            addCriterion("313_Status like", value, "status313");
            return (Criteria) this;
        }

        public Criteria andStatus313NotLike(String value) {
            addCriterion("313_Status not like", value, "status313");
            return (Criteria) this;
        }

        public Criteria andStatus313In(List<String> values) {
            addCriterion("313_Status in", values, "status313");
            return (Criteria) this;
        }

        public Criteria andStatus313NotIn(List<String> values) {
            addCriterion("313_Status not in", values, "status313");
            return (Criteria) this;
        }

        public Criteria andStatus313Between(String value1, String value2) {
            addCriterion("313_Status between", value1, value2, "status313");
            return (Criteria) this;
        }

        public Criteria andStatus313NotBetween(String value1, String value2) {
            addCriterion("313_Status not between", value1, value2, "status313");
            return (Criteria) this;
        }

        public Criteria andStatus315IsNull() {
            addCriterion("315_Status is null");
            return (Criteria) this;
        }

        public Criteria andStatus315IsNotNull() {
            addCriterion("315_Status is not null");
            return (Criteria) this;
        }

        public Criteria andStatus315EqualTo(String value) {
            addCriterion("315_Status =", value, "status315");
            return (Criteria) this;
        }

        public Criteria andStatus315NotEqualTo(String value) {
            addCriterion("315_Status <>", value, "status315");
            return (Criteria) this;
        }

        public Criteria andStatus315GreaterThan(String value) {
            addCriterion("315_Status >", value, "status315");
            return (Criteria) this;
        }

        public Criteria andStatus315GreaterThanOrEqualTo(String value) {
            addCriterion("315_Status >=", value, "status315");
            return (Criteria) this;
        }

        public Criteria andStatus315LessThan(String value) {
            addCriterion("315_Status <", value, "status315");
            return (Criteria) this;
        }

        public Criteria andStatus315LessThanOrEqualTo(String value) {
            addCriterion("315_Status <=", value, "status315");
            return (Criteria) this;
        }

        public Criteria andStatus315Like(String value) {
            addCriterion("315_Status like", value, "status315");
            return (Criteria) this;
        }

        public Criteria andStatus315NotLike(String value) {
            addCriterion("315_Status not like", value, "status315");
            return (Criteria) this;
        }

        public Criteria andStatus315In(List<String> values) {
            addCriterion("315_Status in", values, "status315");
            return (Criteria) this;
        }

        public Criteria andStatus315NotIn(List<String> values) {
            addCriterion("315_Status not in", values, "status315");
            return (Criteria) this;
        }

        public Criteria andStatus315Between(String value1, String value2) {
            addCriterion("315_Status between", value1, value2, "status315");
            return (Criteria) this;
        }

        public Criteria andStatus315NotBetween(String value1, String value2) {
            addCriterion("315_Status not between", value1, value2, "status315");
            return (Criteria) this;
        }

        public Criteria andPlantIsNull() {
            addCriterion("plant is null");
            return (Criteria) this;
        }

        public Criteria andPlantIsNotNull() {
            addCriterion("plant is not null");
            return (Criteria) this;
        }

        public Criteria andPlantEqualTo(String value) {
            addCriterion("plant =", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantNotEqualTo(String value) {
            addCriterion("plant <>", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantGreaterThan(String value) {
            addCriterion("plant >", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantGreaterThanOrEqualTo(String value) {
            addCriterion("plant >=", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantLessThan(String value) {
            addCriterion("plant <", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantLessThanOrEqualTo(String value) {
            addCriterion("plant <=", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantLike(String value) {
            addCriterion("plant like", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantNotLike(String value) {
            addCriterion("plant not like", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantIn(List<String> values) {
            addCriterion("plant in", values, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantNotIn(List<String> values) {
            addCriterion("plant not in", values, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantBetween(String value1, String value2) {
            addCriterion("plant between", value1, value2, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantNotBetween(String value1, String value2) {
            addCriterion("plant not between", value1, value2, "plant");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DL_PCBAInventory
     *
     * @mbggenerated do_not_delete_during_merge Mon Jul 18 14:52:27 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DL_PCBAInventory
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}