package com.ht.entity;

import java.util.Date;

public class InventoryTakeDownEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBAInventoryTakeDown.ID
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    private String ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBAInventoryTakeDown.WO
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    private String WO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBAInventoryTakeDown.WOQuantity
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    private Double WOQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBAInventoryTakeDown.UID
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    private String UID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBAInventoryTakeDown.PartNumber
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    private String partNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBAInventoryTakeDown.Factory
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    private String factory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBAInventoryTakeDown.Location
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBAInventoryTakeDown.AvailableQuantity
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    private Double availableQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBAInventoryTakeDown.AvailableBatch
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    private String availableBatch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBAInventoryTakeDown.CreateUser
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBAInventoryTakeDown.CreateTime
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBAInventoryTakeDown.workcenter
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    private String workCenter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBAInventoryTakeDown.plant
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    private String plant;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBAInventoryTakeDown.ID
     *
     * @return the value of DL_PCBAInventoryTakeDown.ID
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public String getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBAInventoryTakeDown.ID
     *
     * @param ID the value for DL_PCBAInventoryTakeDown.ID
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public void setID(String ID) {
        this.ID = ID == null ? null : ID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBAInventoryTakeDown.WO
     *
     * @return the value of DL_PCBAInventoryTakeDown.WO
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public String getWO() {
        return WO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBAInventoryTakeDown.WO
     *
     * @param WO the value for DL_PCBAInventoryTakeDown.WO
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public void setWO(String WO) {
        this.WO = WO == null ? null : WO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBAInventoryTakeDown.WOQuantity
     *
     * @return the value of DL_PCBAInventoryTakeDown.WOQuantity
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public Double getWOQuantity() {
        return WOQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBAInventoryTakeDown.WOQuantity
     *
     * @param WOQuantity the value for DL_PCBAInventoryTakeDown.WOQuantity
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public void setWOQuantity(Double WOQuantity) {
        this.WOQuantity = WOQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBAInventoryTakeDown.UID
     *
     * @return the value of DL_PCBAInventoryTakeDown.UID
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public String getUID() {
        return UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBAInventoryTakeDown.UID
     *
     * @param UID the value for DL_PCBAInventoryTakeDown.UID
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public void setUID(String UID) {
        this.UID = UID == null ? null : UID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBAInventoryTakeDown.PartNumber
     *
     * @return the value of DL_PCBAInventoryTakeDown.PartNumber
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public String getPartNumber() {
        return partNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBAInventoryTakeDown.PartNumber
     *
     * @param partNumber the value for DL_PCBAInventoryTakeDown.PartNumber
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public void setPartNumber(String partNumber) {
        this.partNumber = partNumber == null ? null : partNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBAInventoryTakeDown.Factory
     *
     * @return the value of DL_PCBAInventoryTakeDown.Factory
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public String getFactory() {
        return factory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBAInventoryTakeDown.Factory
     *
     * @param factory the value for DL_PCBAInventoryTakeDown.Factory
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public void setFactory(String factory) {
        this.factory = factory == null ? null : factory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBAInventoryTakeDown.Location
     *
     * @return the value of DL_PCBAInventoryTakeDown.Location
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBAInventoryTakeDown.Location
     *
     * @param location the value for DL_PCBAInventoryTakeDown.Location
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBAInventoryTakeDown.AvailableQuantity
     *
     * @return the value of DL_PCBAInventoryTakeDown.AvailableQuantity
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public Double getAvailableQuantity() {
        return availableQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBAInventoryTakeDown.AvailableQuantity
     *
     * @param availableQuantity the value for DL_PCBAInventoryTakeDown.AvailableQuantity
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public void setAvailableQuantity(Double availableQuantity) {
        this.availableQuantity = availableQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBAInventoryTakeDown.AvailableBatch
     *
     * @return the value of DL_PCBAInventoryTakeDown.AvailableBatch
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public String getAvailableBatch() {
        return availableBatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBAInventoryTakeDown.AvailableBatch
     *
     * @param availableBatch the value for DL_PCBAInventoryTakeDown.AvailableBatch
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public void setAvailableBatch(String availableBatch) {
        this.availableBatch = availableBatch == null ? null : availableBatch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBAInventoryTakeDown.CreateUser
     *
     * @return the value of DL_PCBAInventoryTakeDown.CreateUser
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBAInventoryTakeDown.CreateUser
     *
     * @param createUser the value for DL_PCBAInventoryTakeDown.CreateUser
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBAInventoryTakeDown.CreateTime
     *
     * @return the value of DL_PCBAInventoryTakeDown.CreateTime
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBAInventoryTakeDown.CreateTime
     *
     * @param createTime the value for DL_PCBAInventoryTakeDown.CreateTime
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBAInventoryTakeDown.workcenter
     *
     * @return the value of DL_PCBAInventoryTakeDown.workcenter
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public String getWorkCenter() {
        return workCenter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBAInventoryTakeDown.workcenter
     *
     * @param workCenter the value for DL_PCBAInventoryTakeDown.workcenter
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public void setWorkCenter(String workCenter) {
        this.workCenter = workCenter == null ? null : workCenter.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBAInventoryTakeDown.plant
     *
     * @return the value of DL_PCBAInventoryTakeDown.plant
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public String getPlant() {
        return plant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBAInventoryTakeDown.plant
     *
     * @param plant the value for DL_PCBAInventoryTakeDown.plant
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    public void setPlant(String plant) {
        this.plant = plant == null ? null : plant.trim();
    }
}