package com.ht.entity;

import io.swagger.annotations.ApiModel;
import org.apache.ibatis.annotations.Mapper;

import java.util.Date;

@Mapper
@ApiModel(value = "SMT发料实体")
public class PCBASMT {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBASMT.ID
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBASMT.WO
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    private String wo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBASMT.WOQTY
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    private Double woqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBASMT.UID
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBASMT.PartNumber
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    private String partnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBASMT.ReceiveBatch
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    private String receivebatch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBASMT.RecLocation
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    private String reclocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBASMT.ReceiveUser
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    private String receiveuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBASMT.ReceiveBatchQTY
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    private Double receivebatchqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBASMT.ReceiveTime
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    private Date receivetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBASMT.Status
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBASMT.SendingBatch
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    private String sendingbatch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBASMT.SendingBatchQTY
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    private Double sendingbatchqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBASMT.SendLocation
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    private String sendlocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBASMT.SendingUser
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    private String sendinguser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBASMT.SendingTime
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    private Date sendingtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBASMT.TotalSentQTY
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    private Double totalsentqty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBASMT.CreateUser
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    private String createuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DL_PCBASMT.CreateTime
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBASMT.ID
     *
     * @return the value of DL_PCBASMT.ID
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBASMT.ID
     *
     * @param id the value for DL_PCBASMT.ID
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBASMT.WO
     *
     * @return the value of DL_PCBASMT.WO
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public String getWo() {
        return wo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBASMT.WO
     *
     * @param wo the value for DL_PCBASMT.WO
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public void setWo(String wo) {
        this.wo = wo == null ? null : wo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBASMT.WOQTY
     *
     * @return the value of DL_PCBASMT.WOQTY
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public Double getWoqty() {
        return woqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBASMT.WOQTY
     *
     * @param woqty the value for DL_PCBASMT.WOQTY
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public void setWoqty(Double woqty) {
        this.woqty = woqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBASMT.UID
     *
     * @return the value of DL_PCBASMT.UID
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBASMT.UID
     *
     * @param uid the value for DL_PCBASMT.UID
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBASMT.PartNumber
     *
     * @return the value of DL_PCBASMT.PartNumber
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public String getPartnumber() {
        return partnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBASMT.PartNumber
     *
     * @param partnumber the value for DL_PCBASMT.PartNumber
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public void setPartnumber(String partnumber) {
        this.partnumber = partnumber == null ? null : partnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBASMT.ReceiveBatch
     *
     * @return the value of DL_PCBASMT.ReceiveBatch
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public String getReceivebatch() {
        return receivebatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBASMT.ReceiveBatch
     *
     * @param receivebatch the value for DL_PCBASMT.ReceiveBatch
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public void setReceivebatch(String receivebatch) {
        this.receivebatch = receivebatch == null ? null : receivebatch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBASMT.RecLocation
     *
     * @return the value of DL_PCBASMT.RecLocation
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public String getReclocation() {
        return reclocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBASMT.RecLocation
     *
     * @param reclocation the value for DL_PCBASMT.RecLocation
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public void setReclocation(String reclocation) {
        this.reclocation = reclocation == null ? null : reclocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBASMT.ReceiveUser
     *
     * @return the value of DL_PCBASMT.ReceiveUser
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public String getReceiveuser() {
        return receiveuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBASMT.ReceiveUser
     *
     * @param receiveuser the value for DL_PCBASMT.ReceiveUser
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public void setReceiveuser(String receiveuser) {
        this.receiveuser = receiveuser == null ? null : receiveuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBASMT.ReceiveBatchQTY
     *
     * @return the value of DL_PCBASMT.ReceiveBatchQTY
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public Double getReceivebatchqty() {
        return receivebatchqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBASMT.ReceiveBatchQTY
     *
     * @param receivebatchqty the value for DL_PCBASMT.ReceiveBatchQTY
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public void setReceivebatchqty(Double receivebatchqty) {
        this.receivebatchqty = receivebatchqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBASMT.ReceiveTime
     *
     * @return the value of DL_PCBASMT.ReceiveTime
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public Date getReceivetime() {
        return receivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBASMT.ReceiveTime
     *
     * @param receivetime the value for DL_PCBASMT.ReceiveTime
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public void setReceivetime(Date receivetime) {
        this.receivetime = receivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBASMT.Status
     *
     * @return the value of DL_PCBASMT.Status
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBASMT.Status
     *
     * @param status the value for DL_PCBASMT.Status
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBASMT.SendingBatch
     *
     * @return the value of DL_PCBASMT.SendingBatch
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public String getSendingbatch() {
        return sendingbatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBASMT.SendingBatch
     *
     * @param sendingbatch the value for DL_PCBASMT.SendingBatch
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public void setSendingbatch(String sendingbatch) {
        this.sendingbatch = sendingbatch == null ? null : sendingbatch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBASMT.SendingBatchQTY
     *
     * @return the value of DL_PCBASMT.SendingBatchQTY
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public Double getSendingbatchqty() {
        return sendingbatchqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBASMT.SendingBatchQTY
     *
     * @param sendingbatchqty the value for DL_PCBASMT.SendingBatchQTY
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public void setSendingbatchqty(Double sendingbatchqty) {
        this.sendingbatchqty = sendingbatchqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBASMT.SendLocation
     *
     * @return the value of DL_PCBASMT.SendLocation
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public String getSendlocation() {
        return sendlocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBASMT.SendLocation
     *
     * @param sendlocation the value for DL_PCBASMT.SendLocation
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public void setSendlocation(String sendlocation) {
        this.sendlocation = sendlocation == null ? null : sendlocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBASMT.SendingUser
     *
     * @return the value of DL_PCBASMT.SendingUser
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public String getSendinguser() {
        return sendinguser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBASMT.SendingUser
     *
     * @param sendinguser the value for DL_PCBASMT.SendingUser
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public void setSendinguser(String sendinguser) {
        this.sendinguser = sendinguser == null ? null : sendinguser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBASMT.SendingTime
     *
     * @return the value of DL_PCBASMT.SendingTime
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public Date getSendingtime() {
        return sendingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBASMT.SendingTime
     *
     * @param sendingtime the value for DL_PCBASMT.SendingTime
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public void setSendingtime(Date sendingtime) {
        this.sendingtime = sendingtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBASMT.TotalSentQTY
     *
     * @return the value of DL_PCBASMT.TotalSentQTY
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public Double getTotalsentqty() {
        return totalsentqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBASMT.TotalSentQTY
     *
     * @param totalsentqty the value for DL_PCBASMT.TotalSentQTY
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public void setTotalsentqty(Double totalsentqty) {
        this.totalsentqty = totalsentqty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBASMT.CreateUser
     *
     * @return the value of DL_PCBASMT.CreateUser
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBASMT.CreateUser
     *
     * @param createuser the value for DL_PCBASMT.CreateUser
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser == null ? null : createuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DL_PCBASMT.CreateTime
     *
     * @return the value of DL_PCBASMT.CreateTime
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DL_PCBASMT.CreateTime
     *
     * @param createtime the value for DL_PCBASMT.CreateTime
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}