package com.ht.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PCBAMIExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DL_PCBAMI
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DL_PCBAMI
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DL_PCBAMI
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAMI
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public PCBAMIExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAMI
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAMI
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAMI
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAMI
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAMI
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAMI
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAMI
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAMI
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAMI
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAMI
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DL_PCBAMI
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andWoIsNull() {
            addCriterion("WO is null");
            return (Criteria) this;
        }

        public Criteria andWoIsNotNull() {
            addCriterion("WO is not null");
            return (Criteria) this;
        }

        public Criteria andWoEqualTo(String value) {
            addCriterion("WO =", value, "wo");
            return (Criteria) this;
        }

        public Criteria andWoNotEqualTo(String value) {
            addCriterion("WO <>", value, "wo");
            return (Criteria) this;
        }

        public Criteria andWoGreaterThan(String value) {
            addCriterion("WO >", value, "wo");
            return (Criteria) this;
        }

        public Criteria andWoGreaterThanOrEqualTo(String value) {
            addCriterion("WO >=", value, "wo");
            return (Criteria) this;
        }

        public Criteria andWoLessThan(String value) {
            addCriterion("WO <", value, "wo");
            return (Criteria) this;
        }

        public Criteria andWoLessThanOrEqualTo(String value) {
            addCriterion("WO <=", value, "wo");
            return (Criteria) this;
        }

        public Criteria andWoLike(String value) {
            addCriterion("WO like", value, "wo");
            return (Criteria) this;
        }

        public Criteria andWoNotLike(String value) {
            addCriterion("WO not like", value, "wo");
            return (Criteria) this;
        }

        public Criteria andWoIn(List<String> values) {
            addCriterion("WO in", values, "wo");
            return (Criteria) this;
        }

        public Criteria andWoNotIn(List<String> values) {
            addCriterion("WO not in", values, "wo");
            return (Criteria) this;
        }

        public Criteria andWoBetween(String value1, String value2) {
            addCriterion("WO between", value1, value2, "wo");
            return (Criteria) this;
        }

        public Criteria andWoNotBetween(String value1, String value2) {
            addCriterion("WO not between", value1, value2, "wo");
            return (Criteria) this;
        }

        public Criteria andWoqtyIsNull() {
            addCriterion("WOQTY is null");
            return (Criteria) this;
        }

        public Criteria andWoqtyIsNotNull() {
            addCriterion("WOQTY is not null");
            return (Criteria) this;
        }

        public Criteria andWoqtyEqualTo(Double value) {
            addCriterion("WOQTY =", value, "woqty");
            return (Criteria) this;
        }

        public Criteria andWoqtyNotEqualTo(Double value) {
            addCriterion("WOQTY <>", value, "woqty");
            return (Criteria) this;
        }

        public Criteria andWoqtyGreaterThan(Double value) {
            addCriterion("WOQTY >", value, "woqty");
            return (Criteria) this;
        }

        public Criteria andWoqtyGreaterThanOrEqualTo(Double value) {
            addCriterion("WOQTY >=", value, "woqty");
            return (Criteria) this;
        }

        public Criteria andWoqtyLessThan(Double value) {
            addCriterion("WOQTY <", value, "woqty");
            return (Criteria) this;
        }

        public Criteria andWoqtyLessThanOrEqualTo(Double value) {
            addCriterion("WOQTY <=", value, "woqty");
            return (Criteria) this;
        }

        public Criteria andWoqtyIn(List<Double> values) {
            addCriterion("WOQTY in", values, "woqty");
            return (Criteria) this;
        }

        public Criteria andWoqtyNotIn(List<Double> values) {
            addCriterion("WOQTY not in", values, "woqty");
            return (Criteria) this;
        }

        public Criteria andWoqtyBetween(Double value1, Double value2) {
            addCriterion("WOQTY between", value1, value2, "woqty");
            return (Criteria) this;
        }

        public Criteria andWoqtyNotBetween(Double value1, Double value2) {
            addCriterion("WOQTY not between", value1, value2, "woqty");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("UID is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("UID is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(String value) {
            addCriterion("UID =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(String value) {
            addCriterion("UID <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(String value) {
            addCriterion("UID >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(String value) {
            addCriterion("UID >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(String value) {
            addCriterion("UID <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(String value) {
            addCriterion("UID <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLike(String value) {
            addCriterion("UID like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotLike(String value) {
            addCriterion("UID not like", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<String> values) {
            addCriterion("UID in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<String> values) {
            addCriterion("UID not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(String value1, String value2) {
            addCriterion("UID between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(String value1, String value2) {
            addCriterion("UID not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andPartnumberIsNull() {
            addCriterion("PartNumber is null");
            return (Criteria) this;
        }

        public Criteria andPartnumberIsNotNull() {
            addCriterion("PartNumber is not null");
            return (Criteria) this;
        }

        public Criteria andPartnumberEqualTo(String value) {
            addCriterion("PartNumber =", value, "partnumber");
            return (Criteria) this;
        }

        public Criteria andPartnumberNotEqualTo(String value) {
            addCriterion("PartNumber <>", value, "partnumber");
            return (Criteria) this;
        }

        public Criteria andPartnumberGreaterThan(String value) {
            addCriterion("PartNumber >", value, "partnumber");
            return (Criteria) this;
        }

        public Criteria andPartnumberGreaterThanOrEqualTo(String value) {
            addCriterion("PartNumber >=", value, "partnumber");
            return (Criteria) this;
        }

        public Criteria andPartnumberLessThan(String value) {
            addCriterion("PartNumber <", value, "partnumber");
            return (Criteria) this;
        }

        public Criteria andPartnumberLessThanOrEqualTo(String value) {
            addCriterion("PartNumber <=", value, "partnumber");
            return (Criteria) this;
        }

        public Criteria andPartnumberLike(String value) {
            addCriterion("PartNumber like", value, "partnumber");
            return (Criteria) this;
        }

        public Criteria andPartnumberNotLike(String value) {
            addCriterion("PartNumber not like", value, "partnumber");
            return (Criteria) this;
        }

        public Criteria andPartnumberIn(List<String> values) {
            addCriterion("PartNumber in", values, "partnumber");
            return (Criteria) this;
        }

        public Criteria andPartnumberNotIn(List<String> values) {
            addCriterion("PartNumber not in", values, "partnumber");
            return (Criteria) this;
        }

        public Criteria andPartnumberBetween(String value1, String value2) {
            addCriterion("PartNumber between", value1, value2, "partnumber");
            return (Criteria) this;
        }

        public Criteria andPartnumberNotBetween(String value1, String value2) {
            addCriterion("PartNumber not between", value1, value2, "partnumber");
            return (Criteria) this;
        }

        public Criteria andReceivebatchIsNull() {
            addCriterion("ReceiveBatch is null");
            return (Criteria) this;
        }

        public Criteria andReceivebatchIsNotNull() {
            addCriterion("ReceiveBatch is not null");
            return (Criteria) this;
        }

        public Criteria andReceivebatchEqualTo(String value) {
            addCriterion("ReceiveBatch =", value, "receivebatch");
            return (Criteria) this;
        }

        public Criteria andReceivebatchNotEqualTo(String value) {
            addCriterion("ReceiveBatch <>", value, "receivebatch");
            return (Criteria) this;
        }

        public Criteria andReceivebatchGreaterThan(String value) {
            addCriterion("ReceiveBatch >", value, "receivebatch");
            return (Criteria) this;
        }

        public Criteria andReceivebatchGreaterThanOrEqualTo(String value) {
            addCriterion("ReceiveBatch >=", value, "receivebatch");
            return (Criteria) this;
        }

        public Criteria andReceivebatchLessThan(String value) {
            addCriterion("ReceiveBatch <", value, "receivebatch");
            return (Criteria) this;
        }

        public Criteria andReceivebatchLessThanOrEqualTo(String value) {
            addCriterion("ReceiveBatch <=", value, "receivebatch");
            return (Criteria) this;
        }

        public Criteria andReceivebatchLike(String value) {
            addCriterion("ReceiveBatch like", value, "receivebatch");
            return (Criteria) this;
        }

        public Criteria andReceivebatchNotLike(String value) {
            addCriterion("ReceiveBatch not like", value, "receivebatch");
            return (Criteria) this;
        }

        public Criteria andReceivebatchIn(List<String> values) {
            addCriterion("ReceiveBatch in", values, "receivebatch");
            return (Criteria) this;
        }

        public Criteria andReceivebatchNotIn(List<String> values) {
            addCriterion("ReceiveBatch not in", values, "receivebatch");
            return (Criteria) this;
        }

        public Criteria andReceivebatchBetween(String value1, String value2) {
            addCriterion("ReceiveBatch between", value1, value2, "receivebatch");
            return (Criteria) this;
        }

        public Criteria andReceivebatchNotBetween(String value1, String value2) {
            addCriterion("ReceiveBatch not between", value1, value2, "receivebatch");
            return (Criteria) this;
        }

        public Criteria andReclocationIsNull() {
            addCriterion("RecLocation is null");
            return (Criteria) this;
        }

        public Criteria andReclocationIsNotNull() {
            addCriterion("RecLocation is not null");
            return (Criteria) this;
        }

        public Criteria andReclocationEqualTo(String value) {
            addCriterion("RecLocation =", value, "reclocation");
            return (Criteria) this;
        }

        public Criteria andReclocationNotEqualTo(String value) {
            addCriterion("RecLocation <>", value, "reclocation");
            return (Criteria) this;
        }

        public Criteria andReclocationGreaterThan(String value) {
            addCriterion("RecLocation >", value, "reclocation");
            return (Criteria) this;
        }

        public Criteria andReclocationGreaterThanOrEqualTo(String value) {
            addCriterion("RecLocation >=", value, "reclocation");
            return (Criteria) this;
        }

        public Criteria andReclocationLessThan(String value) {
            addCriterion("RecLocation <", value, "reclocation");
            return (Criteria) this;
        }

        public Criteria andReclocationLessThanOrEqualTo(String value) {
            addCriterion("RecLocation <=", value, "reclocation");
            return (Criteria) this;
        }

        public Criteria andReclocationLike(String value) {
            addCriterion("RecLocation like", value, "reclocation");
            return (Criteria) this;
        }

        public Criteria andReclocationNotLike(String value) {
            addCriterion("RecLocation not like", value, "reclocation");
            return (Criteria) this;
        }

        public Criteria andReclocationIn(List<String> values) {
            addCriterion("RecLocation in", values, "reclocation");
            return (Criteria) this;
        }

        public Criteria andReclocationNotIn(List<String> values) {
            addCriterion("RecLocation not in", values, "reclocation");
            return (Criteria) this;
        }

        public Criteria andReclocationBetween(String value1, String value2) {
            addCriterion("RecLocation between", value1, value2, "reclocation");
            return (Criteria) this;
        }

        public Criteria andReclocationNotBetween(String value1, String value2) {
            addCriterion("RecLocation not between", value1, value2, "reclocation");
            return (Criteria) this;
        }

        public Criteria andReceiveuserIsNull() {
            addCriterion("ReceiveUser is null");
            return (Criteria) this;
        }

        public Criteria andReceiveuserIsNotNull() {
            addCriterion("ReceiveUser is not null");
            return (Criteria) this;
        }

        public Criteria andReceiveuserEqualTo(String value) {
            addCriterion("ReceiveUser =", value, "receiveuser");
            return (Criteria) this;
        }

        public Criteria andReceiveuserNotEqualTo(String value) {
            addCriterion("ReceiveUser <>", value, "receiveuser");
            return (Criteria) this;
        }

        public Criteria andReceiveuserGreaterThan(String value) {
            addCriterion("ReceiveUser >", value, "receiveuser");
            return (Criteria) this;
        }

        public Criteria andReceiveuserGreaterThanOrEqualTo(String value) {
            addCriterion("ReceiveUser >=", value, "receiveuser");
            return (Criteria) this;
        }

        public Criteria andReceiveuserLessThan(String value) {
            addCriterion("ReceiveUser <", value, "receiveuser");
            return (Criteria) this;
        }

        public Criteria andReceiveuserLessThanOrEqualTo(String value) {
            addCriterion("ReceiveUser <=", value, "receiveuser");
            return (Criteria) this;
        }

        public Criteria andReceiveuserLike(String value) {
            addCriterion("ReceiveUser like", value, "receiveuser");
            return (Criteria) this;
        }

        public Criteria andReceiveuserNotLike(String value) {
            addCriterion("ReceiveUser not like", value, "receiveuser");
            return (Criteria) this;
        }

        public Criteria andReceiveuserIn(List<String> values) {
            addCriterion("ReceiveUser in", values, "receiveuser");
            return (Criteria) this;
        }

        public Criteria andReceiveuserNotIn(List<String> values) {
            addCriterion("ReceiveUser not in", values, "receiveuser");
            return (Criteria) this;
        }

        public Criteria andReceiveuserBetween(String value1, String value2) {
            addCriterion("ReceiveUser between", value1, value2, "receiveuser");
            return (Criteria) this;
        }

        public Criteria andReceiveuserNotBetween(String value1, String value2) {
            addCriterion("ReceiveUser not between", value1, value2, "receiveuser");
            return (Criteria) this;
        }

        public Criteria andReceivebatchqtyIsNull() {
            addCriterion("ReceiveBatchQTY is null");
            return (Criteria) this;
        }

        public Criteria andReceivebatchqtyIsNotNull() {
            addCriterion("ReceiveBatchQTY is not null");
            return (Criteria) this;
        }

        public Criteria andReceivebatchqtyEqualTo(Double value) {
            addCriterion("ReceiveBatchQTY =", value, "receivebatchqty");
            return (Criteria) this;
        }

        public Criteria andReceivebatchqtyNotEqualTo(Double value) {
            addCriterion("ReceiveBatchQTY <>", value, "receivebatchqty");
            return (Criteria) this;
        }

        public Criteria andReceivebatchqtyGreaterThan(Double value) {
            addCriterion("ReceiveBatchQTY >", value, "receivebatchqty");
            return (Criteria) this;
        }

        public Criteria andReceivebatchqtyGreaterThanOrEqualTo(Double value) {
            addCriterion("ReceiveBatchQTY >=", value, "receivebatchqty");
            return (Criteria) this;
        }

        public Criteria andReceivebatchqtyLessThan(Double value) {
            addCriterion("ReceiveBatchQTY <", value, "receivebatchqty");
            return (Criteria) this;
        }

        public Criteria andReceivebatchqtyLessThanOrEqualTo(Double value) {
            addCriterion("ReceiveBatchQTY <=", value, "receivebatchqty");
            return (Criteria) this;
        }

        public Criteria andReceivebatchqtyIn(List<Double> values) {
            addCriterion("ReceiveBatchQTY in", values, "receivebatchqty");
            return (Criteria) this;
        }

        public Criteria andReceivebatchqtyNotIn(List<Double> values) {
            addCriterion("ReceiveBatchQTY not in", values, "receivebatchqty");
            return (Criteria) this;
        }

        public Criteria andReceivebatchqtyBetween(Double value1, Double value2) {
            addCriterion("ReceiveBatchQTY between", value1, value2, "receivebatchqty");
            return (Criteria) this;
        }

        public Criteria andReceivebatchqtyNotBetween(Double value1, Double value2) {
            addCriterion("ReceiveBatchQTY not between", value1, value2, "receivebatchqty");
            return (Criteria) this;
        }

        public Criteria andReceivetimeIsNull() {
            addCriterion("ReceiveTime is null");
            return (Criteria) this;
        }

        public Criteria andReceivetimeIsNotNull() {
            addCriterion("ReceiveTime is not null");
            return (Criteria) this;
        }

        public Criteria andReceivetimeEqualTo(Date value) {
            addCriterion("ReceiveTime =", value, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeNotEqualTo(Date value) {
            addCriterion("ReceiveTime <>", value, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeGreaterThan(Date value) {
            addCriterion("ReceiveTime >", value, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ReceiveTime >=", value, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeLessThan(Date value) {
            addCriterion("ReceiveTime <", value, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeLessThanOrEqualTo(Date value) {
            addCriterion("ReceiveTime <=", value, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeIn(List<Date> values) {
            addCriterion("ReceiveTime in", values, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeNotIn(List<Date> values) {
            addCriterion("ReceiveTime not in", values, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeBetween(Date value1, Date value2) {
            addCriterion("ReceiveTime between", value1, value2, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeNotBetween(Date value1, Date value2) {
            addCriterion("ReceiveTime not between", value1, value2, "receivetime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("Status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("Status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("Status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("Status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("Status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("Status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("Status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("Status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("Status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("Status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("Status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("Status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andSendingbatchIsNull() {
            addCriterion("SendingBatch is null");
            return (Criteria) this;
        }

        public Criteria andSendingbatchIsNotNull() {
            addCriterion("SendingBatch is not null");
            return (Criteria) this;
        }

        public Criteria andSendingbatchEqualTo(String value) {
            addCriterion("SendingBatch =", value, "sendingbatch");
            return (Criteria) this;
        }

        public Criteria andSendingbatchNotEqualTo(String value) {
            addCriterion("SendingBatch <>", value, "sendingbatch");
            return (Criteria) this;
        }

        public Criteria andSendingbatchGreaterThan(String value) {
            addCriterion("SendingBatch >", value, "sendingbatch");
            return (Criteria) this;
        }

        public Criteria andSendingbatchGreaterThanOrEqualTo(String value) {
            addCriterion("SendingBatch >=", value, "sendingbatch");
            return (Criteria) this;
        }

        public Criteria andSendingbatchLessThan(String value) {
            addCriterion("SendingBatch <", value, "sendingbatch");
            return (Criteria) this;
        }

        public Criteria andSendingbatchLessThanOrEqualTo(String value) {
            addCriterion("SendingBatch <=", value, "sendingbatch");
            return (Criteria) this;
        }

        public Criteria andSendingbatchLike(String value) {
            addCriterion("SendingBatch like", value, "sendingbatch");
            return (Criteria) this;
        }

        public Criteria andSendingbatchNotLike(String value) {
            addCriterion("SendingBatch not like", value, "sendingbatch");
            return (Criteria) this;
        }

        public Criteria andSendingbatchIn(List<String> values) {
            addCriterion("SendingBatch in", values, "sendingbatch");
            return (Criteria) this;
        }

        public Criteria andSendingbatchNotIn(List<String> values) {
            addCriterion("SendingBatch not in", values, "sendingbatch");
            return (Criteria) this;
        }

        public Criteria andSendingbatchBetween(String value1, String value2) {
            addCriterion("SendingBatch between", value1, value2, "sendingbatch");
            return (Criteria) this;
        }

        public Criteria andSendingbatchNotBetween(String value1, String value2) {
            addCriterion("SendingBatch not between", value1, value2, "sendingbatch");
            return (Criteria) this;
        }

        public Criteria andSendingbatchqtyIsNull() {
            addCriterion("SendingBatchQTY is null");
            return (Criteria) this;
        }

        public Criteria andSendingbatchqtyIsNotNull() {
            addCriterion("SendingBatchQTY is not null");
            return (Criteria) this;
        }

        public Criteria andSendingbatchqtyEqualTo(Double value) {
            addCriterion("SendingBatchQTY =", value, "sendingbatchqty");
            return (Criteria) this;
        }

        public Criteria andSendingbatchqtyNotEqualTo(Double value) {
            addCriterion("SendingBatchQTY <>", value, "sendingbatchqty");
            return (Criteria) this;
        }

        public Criteria andSendingbatchqtyGreaterThan(Double value) {
            addCriterion("SendingBatchQTY >", value, "sendingbatchqty");
            return (Criteria) this;
        }

        public Criteria andSendingbatchqtyGreaterThanOrEqualTo(Double value) {
            addCriterion("SendingBatchQTY >=", value, "sendingbatchqty");
            return (Criteria) this;
        }

        public Criteria andSendingbatchqtyLessThan(Double value) {
            addCriterion("SendingBatchQTY <", value, "sendingbatchqty");
            return (Criteria) this;
        }

        public Criteria andSendingbatchqtyLessThanOrEqualTo(Double value) {
            addCriterion("SendingBatchQTY <=", value, "sendingbatchqty");
            return (Criteria) this;
        }

        public Criteria andSendingbatchqtyIn(List<Double> values) {
            addCriterion("SendingBatchQTY in", values, "sendingbatchqty");
            return (Criteria) this;
        }

        public Criteria andSendingbatchqtyNotIn(List<Double> values) {
            addCriterion("SendingBatchQTY not in", values, "sendingbatchqty");
            return (Criteria) this;
        }

        public Criteria andSendingbatchqtyBetween(Double value1, Double value2) {
            addCriterion("SendingBatchQTY between", value1, value2, "sendingbatchqty");
            return (Criteria) this;
        }

        public Criteria andSendingbatchqtyNotBetween(Double value1, Double value2) {
            addCriterion("SendingBatchQTY not between", value1, value2, "sendingbatchqty");
            return (Criteria) this;
        }

        public Criteria andSendlocationIsNull() {
            addCriterion("SendLocation is null");
            return (Criteria) this;
        }

        public Criteria andSendlocationIsNotNull() {
            addCriterion("SendLocation is not null");
            return (Criteria) this;
        }

        public Criteria andSendlocationEqualTo(String value) {
            addCriterion("SendLocation =", value, "sendlocation");
            return (Criteria) this;
        }

        public Criteria andSendlocationNotEqualTo(String value) {
            addCriterion("SendLocation <>", value, "sendlocation");
            return (Criteria) this;
        }

        public Criteria andSendlocationGreaterThan(String value) {
            addCriterion("SendLocation >", value, "sendlocation");
            return (Criteria) this;
        }

        public Criteria andSendlocationGreaterThanOrEqualTo(String value) {
            addCriterion("SendLocation >=", value, "sendlocation");
            return (Criteria) this;
        }

        public Criteria andSendlocationLessThan(String value) {
            addCriterion("SendLocation <", value, "sendlocation");
            return (Criteria) this;
        }

        public Criteria andSendlocationLessThanOrEqualTo(String value) {
            addCriterion("SendLocation <=", value, "sendlocation");
            return (Criteria) this;
        }

        public Criteria andSendlocationLike(String value) {
            addCriterion("SendLocation like", value, "sendlocation");
            return (Criteria) this;
        }

        public Criteria andSendlocationNotLike(String value) {
            addCriterion("SendLocation not like", value, "sendlocation");
            return (Criteria) this;
        }

        public Criteria andSendlocationIn(List<String> values) {
            addCriterion("SendLocation in", values, "sendlocation");
            return (Criteria) this;
        }

        public Criteria andSendlocationNotIn(List<String> values) {
            addCriterion("SendLocation not in", values, "sendlocation");
            return (Criteria) this;
        }

        public Criteria andSendlocationBetween(String value1, String value2) {
            addCriterion("SendLocation between", value1, value2, "sendlocation");
            return (Criteria) this;
        }

        public Criteria andSendlocationNotBetween(String value1, String value2) {
            addCriterion("SendLocation not between", value1, value2, "sendlocation");
            return (Criteria) this;
        }

        public Criteria andSendinguserIsNull() {
            addCriterion("SendingUser is null");
            return (Criteria) this;
        }

        public Criteria andSendinguserIsNotNull() {
            addCriterion("SendingUser is not null");
            return (Criteria) this;
        }

        public Criteria andSendinguserEqualTo(String value) {
            addCriterion("SendingUser =", value, "sendinguser");
            return (Criteria) this;
        }

        public Criteria andSendinguserNotEqualTo(String value) {
            addCriterion("SendingUser <>", value, "sendinguser");
            return (Criteria) this;
        }

        public Criteria andSendinguserGreaterThan(String value) {
            addCriterion("SendingUser >", value, "sendinguser");
            return (Criteria) this;
        }

        public Criteria andSendinguserGreaterThanOrEqualTo(String value) {
            addCriterion("SendingUser >=", value, "sendinguser");
            return (Criteria) this;
        }

        public Criteria andSendinguserLessThan(String value) {
            addCriterion("SendingUser <", value, "sendinguser");
            return (Criteria) this;
        }

        public Criteria andSendinguserLessThanOrEqualTo(String value) {
            addCriterion("SendingUser <=", value, "sendinguser");
            return (Criteria) this;
        }

        public Criteria andSendinguserLike(String value) {
            addCriterion("SendingUser like", value, "sendinguser");
            return (Criteria) this;
        }

        public Criteria andSendinguserNotLike(String value) {
            addCriterion("SendingUser not like", value, "sendinguser");
            return (Criteria) this;
        }

        public Criteria andSendinguserIn(List<String> values) {
            addCriterion("SendingUser in", values, "sendinguser");
            return (Criteria) this;
        }

        public Criteria andSendinguserNotIn(List<String> values) {
            addCriterion("SendingUser not in", values, "sendinguser");
            return (Criteria) this;
        }

        public Criteria andSendinguserBetween(String value1, String value2) {
            addCriterion("SendingUser between", value1, value2, "sendinguser");
            return (Criteria) this;
        }

        public Criteria andSendinguserNotBetween(String value1, String value2) {
            addCriterion("SendingUser not between", value1, value2, "sendinguser");
            return (Criteria) this;
        }

        public Criteria andSendingtimeIsNull() {
            addCriterion("SendingTime is null");
            return (Criteria) this;
        }

        public Criteria andSendingtimeIsNotNull() {
            addCriterion("SendingTime is not null");
            return (Criteria) this;
        }

        public Criteria andSendingtimeEqualTo(Date value) {
            addCriterion("SendingTime =", value, "sendingtime");
            return (Criteria) this;
        }

        public Criteria andSendingtimeNotEqualTo(Date value) {
            addCriterion("SendingTime <>", value, "sendingtime");
            return (Criteria) this;
        }

        public Criteria andSendingtimeGreaterThan(Date value) {
            addCriterion("SendingTime >", value, "sendingtime");
            return (Criteria) this;
        }

        public Criteria andSendingtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SendingTime >=", value, "sendingtime");
            return (Criteria) this;
        }

        public Criteria andSendingtimeLessThan(Date value) {
            addCriterion("SendingTime <", value, "sendingtime");
            return (Criteria) this;
        }

        public Criteria andSendingtimeLessThanOrEqualTo(Date value) {
            addCriterion("SendingTime <=", value, "sendingtime");
            return (Criteria) this;
        }

        public Criteria andSendingtimeIn(List<Date> values) {
            addCriterion("SendingTime in", values, "sendingtime");
            return (Criteria) this;
        }

        public Criteria andSendingtimeNotIn(List<Date> values) {
            addCriterion("SendingTime not in", values, "sendingtime");
            return (Criteria) this;
        }

        public Criteria andSendingtimeBetween(Date value1, Date value2) {
            addCriterion("SendingTime between", value1, value2, "sendingtime");
            return (Criteria) this;
        }

        public Criteria andSendingtimeNotBetween(Date value1, Date value2) {
            addCriterion("SendingTime not between", value1, value2, "sendingtime");
            return (Criteria) this;
        }

        public Criteria andTotalsentqtyIsNull() {
            addCriterion("TotalSentQTY is null");
            return (Criteria) this;
        }

        public Criteria andTotalsentqtyIsNotNull() {
            addCriterion("TotalSentQTY is not null");
            return (Criteria) this;
        }

        public Criteria andTotalsentqtyEqualTo(Double value) {
            addCriterion("TotalSentQTY =", value, "totalsentqty");
            return (Criteria) this;
        }

        public Criteria andTotalsentqtyNotEqualTo(Double value) {
            addCriterion("TotalSentQTY <>", value, "totalsentqty");
            return (Criteria) this;
        }

        public Criteria andTotalsentqtyGreaterThan(Double value) {
            addCriterion("TotalSentQTY >", value, "totalsentqty");
            return (Criteria) this;
        }

        public Criteria andTotalsentqtyGreaterThanOrEqualTo(Double value) {
            addCriterion("TotalSentQTY >=", value, "totalsentqty");
            return (Criteria) this;
        }

        public Criteria andTotalsentqtyLessThan(Double value) {
            addCriterion("TotalSentQTY <", value, "totalsentqty");
            return (Criteria) this;
        }

        public Criteria andTotalsentqtyLessThanOrEqualTo(Double value) {
            addCriterion("TotalSentQTY <=", value, "totalsentqty");
            return (Criteria) this;
        }

        public Criteria andTotalsentqtyIn(List<Double> values) {
            addCriterion("TotalSentQTY in", values, "totalsentqty");
            return (Criteria) this;
        }

        public Criteria andTotalsentqtyNotIn(List<Double> values) {
            addCriterion("TotalSentQTY not in", values, "totalsentqty");
            return (Criteria) this;
        }

        public Criteria andTotalsentqtyBetween(Double value1, Double value2) {
            addCriterion("TotalSentQTY between", value1, value2, "totalsentqty");
            return (Criteria) this;
        }

        public Criteria andTotalsentqtyNotBetween(Double value1, Double value2) {
            addCriterion("TotalSentQTY not between", value1, value2, "totalsentqty");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNull() {
            addCriterion("CreateUser is null");
            return (Criteria) this;
        }

        public Criteria andCreateuserIsNotNull() {
            addCriterion("CreateUser is not null");
            return (Criteria) this;
        }

        public Criteria andCreateuserEqualTo(String value) {
            addCriterion("CreateUser =", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotEqualTo(String value) {
            addCriterion("CreateUser <>", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThan(String value) {
            addCriterion("CreateUser >", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserGreaterThanOrEqualTo(String value) {
            addCriterion("CreateUser >=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThan(String value) {
            addCriterion("CreateUser <", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLessThanOrEqualTo(String value) {
            addCriterion("CreateUser <=", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserLike(String value) {
            addCriterion("CreateUser like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotLike(String value) {
            addCriterion("CreateUser not like", value, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserIn(List<String> values) {
            addCriterion("CreateUser in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotIn(List<String> values) {
            addCriterion("CreateUser not in", values, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserBetween(String value1, String value2) {
            addCriterion("CreateUser between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreateuserNotBetween(String value1, String value2) {
            addCriterion("CreateUser not between", value1, value2, "createuser");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("CreateTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("CreateTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("CreateTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("CreateTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("CreateTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CreateTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("CreateTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("CreateTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("CreateTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("CreateTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("CreateTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("CreateTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DL_PCBAMI
     *
     * @mbggenerated do_not_delete_during_merge Wed Oct 12 15:35:47 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DL_PCBAMI
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}