package com.ht.entity;

public class TransactionGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsGroup.BatchId
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String batchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsGroup.ItemId
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsGroup.TransactionHistoryId
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String transactionHistoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsGroup.BatchId
     *
     * @return the value of xTend_MaterialTransactionsGroup.BatchId
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsGroup.BatchId
     *
     * @param batchId the value for xTend_MaterialTransactionsGroup.BatchId
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setBatchId(String batchId) {
        this.batchId = batchId == null ? null : batchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsGroup.ItemId
     *
     * @return the value of xTend_MaterialTransactionsGroup.ItemId
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsGroup.ItemId
     *
     * @param itemId the value for xTend_MaterialTransactionsGroup.ItemId
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsGroup.TransactionHistoryId
     *
     * @return the value of xTend_MaterialTransactionsGroup.TransactionHistoryId
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getTransactionHistoryId() {
        return transactionHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsGroup.TransactionHistoryId
     *
     * @param transactionHistoryId the value for xTend_MaterialTransactionsGroup.TransactionHistoryId
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setTransactionHistoryId(String transactionHistoryId) {
        this.transactionHistoryId = transactionHistoryId == null ? null : transactionHistoryId.trim();
    }
}