package com.ht.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TransactionLogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xTend_MaterialTxnLog
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xTend_MaterialTxnLog
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xTend_MaterialTxnLog
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTxnLog
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public TransactionLogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTxnLog
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTxnLog
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTxnLog
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTxnLog
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTxnLog
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTxnLog
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTxnLog
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTxnLog
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTxnLog
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTxnLog
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xTend_MaterialTxnLog
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andModuleIsNull() {
            addCriterion("Module is null");
            return (Criteria) this;
        }

        public Criteria andModuleIsNotNull() {
            addCriterion("Module is not null");
            return (Criteria) this;
        }

        public Criteria andModuleEqualTo(String value) {
            addCriterion("Module =", value, "module");
            return (Criteria) this;
        }

        public Criteria andModuleNotEqualTo(String value) {
            addCriterion("Module <>", value, "module");
            return (Criteria) this;
        }

        public Criteria andModuleGreaterThan(String value) {
            addCriterion("Module >", value, "module");
            return (Criteria) this;
        }

        public Criteria andModuleGreaterThanOrEqualTo(String value) {
            addCriterion("Module >=", value, "module");
            return (Criteria) this;
        }

        public Criteria andModuleLessThan(String value) {
            addCriterion("Module <", value, "module");
            return (Criteria) this;
        }

        public Criteria andModuleLessThanOrEqualTo(String value) {
            addCriterion("Module <=", value, "module");
            return (Criteria) this;
        }

        public Criteria andModuleLike(String value) {
            addCriterion("Module like", value, "module");
            return (Criteria) this;
        }

        public Criteria andModuleNotLike(String value) {
            addCriterion("Module not like", value, "module");
            return (Criteria) this;
        }

        public Criteria andModuleIn(List<String> values) {
            addCriterion("Module in", values, "module");
            return (Criteria) this;
        }

        public Criteria andModuleNotIn(List<String> values) {
            addCriterion("Module not in", values, "module");
            return (Criteria) this;
        }

        public Criteria andModuleBetween(String value1, String value2) {
            addCriterion("Module between", value1, value2, "module");
            return (Criteria) this;
        }

        public Criteria andModuleNotBetween(String value1, String value2) {
            addCriterion("Module not between", value1, value2, "module");
            return (Criteria) this;
        }

        public Criteria andTxnTypeIsNull() {
            addCriterion("TxnType is null");
            return (Criteria) this;
        }

        public Criteria andTxnTypeIsNotNull() {
            addCriterion("TxnType is not null");
            return (Criteria) this;
        }

        public Criteria andTxnTypeEqualTo(String value) {
            addCriterion("TxnType =", value, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeNotEqualTo(String value) {
            addCriterion("TxnType <>", value, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeGreaterThan(String value) {
            addCriterion("TxnType >", value, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TxnType >=", value, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeLessThan(String value) {
            addCriterion("TxnType <", value, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeLessThanOrEqualTo(String value) {
            addCriterion("TxnType <=", value, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeLike(String value) {
            addCriterion("TxnType like", value, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeNotLike(String value) {
            addCriterion("TxnType not like", value, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeIn(List<String> values) {
            addCriterion("TxnType in", values, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeNotIn(List<String> values) {
            addCriterion("TxnType not in", values, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeBetween(String value1, String value2) {
            addCriterion("TxnType between", value1, value2, "txnType");
            return (Criteria) this;
        }

        public Criteria andTxnTypeNotBetween(String value1, String value2) {
            addCriterion("TxnType not between", value1, value2, "txnType");
            return (Criteria) this;
        }

        public Criteria andBatchIdIsNull() {
            addCriterion("BatchId is null");
            return (Criteria) this;
        }

        public Criteria andBatchIdIsNotNull() {
            addCriterion("BatchId is not null");
            return (Criteria) this;
        }

        public Criteria andBatchIdEqualTo(String value) {
            addCriterion("BatchId =", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdNotEqualTo(String value) {
            addCriterion("BatchId <>", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdGreaterThan(String value) {
            addCriterion("BatchId >", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdGreaterThanOrEqualTo(String value) {
            addCriterion("BatchId >=", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdLessThan(String value) {
            addCriterion("BatchId <", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdLessThanOrEqualTo(String value) {
            addCriterion("BatchId <=", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdLike(String value) {
            addCriterion("BatchId like", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdNotLike(String value) {
            addCriterion("BatchId not like", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdIn(List<String> values) {
            addCriterion("BatchId in", values, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdNotIn(List<String> values) {
            addCriterion("BatchId not in", values, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdBetween(String value1, String value2) {
            addCriterion("BatchId between", value1, value2, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdNotBetween(String value1, String value2) {
            addCriterion("BatchId not between", value1, value2, "batchId");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNull() {
            addCriterion("ItemId is null");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNotNull() {
            addCriterion("ItemId is not null");
            return (Criteria) this;
        }

        public Criteria andItemIdEqualTo(Integer value) {
            addCriterion("ItemId =", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotEqualTo(Integer value) {
            addCriterion("ItemId <>", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThan(Integer value) {
            addCriterion("ItemId >", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ItemId >=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThan(Integer value) {
            addCriterion("ItemId <", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThanOrEqualTo(Integer value) {
            addCriterion("ItemId <=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdIn(List<Integer> values) {
            addCriterion("ItemId in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotIn(List<Integer> values) {
            addCriterion("ItemId not in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdBetween(Integer value1, Integer value2) {
            addCriterion("ItemId between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ItemId not between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("Time is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("Time is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(Date value) {
            addCriterion("Time =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(Date value) {
            addCriterion("Time <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(Date value) {
            addCriterion("Time >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("Time >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(Date value) {
            addCriterion("Time <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(Date value) {
            addCriterion("Time <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<Date> values) {
            addCriterion("Time in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<Date> values) {
            addCriterion("Time not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(Date value1, Date value2) {
            addCriterion("Time between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(Date value1, Date value2) {
            addCriterion("Time not between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andResultIsNull() {
            addCriterion("Result is null");
            return (Criteria) this;
        }

        public Criteria andResultIsNotNull() {
            addCriterion("Result is not null");
            return (Criteria) this;
        }

        public Criteria andResultEqualTo(String value) {
            addCriterion("Result =", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotEqualTo(String value) {
            addCriterion("Result <>", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultGreaterThan(String value) {
            addCriterion("Result >", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultGreaterThanOrEqualTo(String value) {
            addCriterion("Result >=", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultLessThan(String value) {
            addCriterion("Result <", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultLessThanOrEqualTo(String value) {
            addCriterion("Result <=", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultLike(String value) {
            addCriterion("Result like", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotLike(String value) {
            addCriterion("Result not like", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultIn(List<String> values) {
            addCriterion("Result in", values, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotIn(List<String> values) {
            addCriterion("Result not in", values, "result");
            return (Criteria) this;
        }

        public Criteria andResultBetween(String value1, String value2) {
            addCriterion("Result between", value1, value2, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotBetween(String value1, String value2) {
            addCriterion("Result not between", value1, value2, "result");
            return (Criteria) this;
        }

        public Criteria andMessageIsNull() {
            addCriterion("Message is null");
            return (Criteria) this;
        }

        public Criteria andMessageIsNotNull() {
            addCriterion("Message is not null");
            return (Criteria) this;
        }

        public Criteria andMessageEqualTo(String value) {
            addCriterion("Message =", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotEqualTo(String value) {
            addCriterion("Message <>", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageGreaterThan(String value) {
            addCriterion("Message >", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageGreaterThanOrEqualTo(String value) {
            addCriterion("Message >=", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageLessThan(String value) {
            addCriterion("Message <", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageLessThanOrEqualTo(String value) {
            addCriterion("Message <=", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageLike(String value) {
            addCriterion("Message like", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotLike(String value) {
            addCriterion("Message not like", value, "message");
            return (Criteria) this;
        }

        public Criteria andMessageIn(List<String> values) {
            addCriterion("Message in", values, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotIn(List<String> values) {
            addCriterion("Message not in", values, "message");
            return (Criteria) this;
        }

        public Criteria andMessageBetween(String value1, String value2) {
            addCriterion("Message between", value1, value2, "message");
            return (Criteria) this;
        }

        public Criteria andMessageNotBetween(String value1, String value2) {
            addCriterion("Message not between", value1, value2, "message");
            return (Criteria) this;
        }

        public Criteria andSAPREF_DOCIsNull() {
            addCriterion("SAPREF_DOC is null");
            return (Criteria) this;
        }

        public Criteria andSAPREF_DOCIsNotNull() {
            addCriterion("SAPREF_DOC is not null");
            return (Criteria) this;
        }

        public Criteria andSAPREF_DOCEqualTo(String value) {
            addCriterion("SAPREF_DOC =", value, "SAPREF_DOC");
            return (Criteria) this;
        }

        public Criteria andSAPREF_DOCNotEqualTo(String value) {
            addCriterion("SAPREF_DOC <>", value, "SAPREF_DOC");
            return (Criteria) this;
        }

        public Criteria andSAPREF_DOCGreaterThan(String value) {
            addCriterion("SAPREF_DOC >", value, "SAPREF_DOC");
            return (Criteria) this;
        }

        public Criteria andSAPREF_DOCGreaterThanOrEqualTo(String value) {
            addCriterion("SAPREF_DOC >=", value, "SAPREF_DOC");
            return (Criteria) this;
        }

        public Criteria andSAPREF_DOCLessThan(String value) {
            addCriterion("SAPREF_DOC <", value, "SAPREF_DOC");
            return (Criteria) this;
        }

        public Criteria andSAPREF_DOCLessThanOrEqualTo(String value) {
            addCriterion("SAPREF_DOC <=", value, "SAPREF_DOC");
            return (Criteria) this;
        }

        public Criteria andSAPREF_DOCLike(String value) {
            addCriterion("SAPREF_DOC like", value, "SAPREF_DOC");
            return (Criteria) this;
        }

        public Criteria andSAPREF_DOCNotLike(String value) {
            addCriterion("SAPREF_DOC not like", value, "SAPREF_DOC");
            return (Criteria) this;
        }

        public Criteria andSAPREF_DOCIn(List<String> values) {
            addCriterion("SAPREF_DOC in", values, "SAPREF_DOC");
            return (Criteria) this;
        }

        public Criteria andSAPREF_DOCNotIn(List<String> values) {
            addCriterion("SAPREF_DOC not in", values, "SAPREF_DOC");
            return (Criteria) this;
        }

        public Criteria andSAPREF_DOCBetween(String value1, String value2) {
            addCriterion("SAPREF_DOC between", value1, value2, "SAPREF_DOC");
            return (Criteria) this;
        }

        public Criteria andSAPREF_DOCNotBetween(String value1, String value2) {
            addCriterion("SAPREF_DOC not between", value1, value2, "SAPREF_DOC");
            return (Criteria) this;
        }

        public Criteria andSAPREF_YEARIsNull() {
            addCriterion("SAPREF_YEAR is null");
            return (Criteria) this;
        }

        public Criteria andSAPREF_YEARIsNotNull() {
            addCriterion("SAPREF_YEAR is not null");
            return (Criteria) this;
        }

        public Criteria andSAPREF_YEAREqualTo(String value) {
            addCriterion("SAPREF_YEAR =", value, "SAPREF_YEAR");
            return (Criteria) this;
        }

        public Criteria andSAPREF_YEARNotEqualTo(String value) {
            addCriterion("SAPREF_YEAR <>", value, "SAPREF_YEAR");
            return (Criteria) this;
        }

        public Criteria andSAPREF_YEARGreaterThan(String value) {
            addCriterion("SAPREF_YEAR >", value, "SAPREF_YEAR");
            return (Criteria) this;
        }

        public Criteria andSAPREF_YEARGreaterThanOrEqualTo(String value) {
            addCriterion("SAPREF_YEAR >=", value, "SAPREF_YEAR");
            return (Criteria) this;
        }

        public Criteria andSAPREF_YEARLessThan(String value) {
            addCriterion("SAPREF_YEAR <", value, "SAPREF_YEAR");
            return (Criteria) this;
        }

        public Criteria andSAPREF_YEARLessThanOrEqualTo(String value) {
            addCriterion("SAPREF_YEAR <=", value, "SAPREF_YEAR");
            return (Criteria) this;
        }

        public Criteria andSAPREF_YEARLike(String value) {
            addCriterion("SAPREF_YEAR like", value, "SAPREF_YEAR");
            return (Criteria) this;
        }

        public Criteria andSAPREF_YEARNotLike(String value) {
            addCriterion("SAPREF_YEAR not like", value, "SAPREF_YEAR");
            return (Criteria) this;
        }

        public Criteria andSAPREF_YEARIn(List<String> values) {
            addCriterion("SAPREF_YEAR in", values, "SAPREF_YEAR");
            return (Criteria) this;
        }

        public Criteria andSAPREF_YEARNotIn(List<String> values) {
            addCriterion("SAPREF_YEAR not in", values, "SAPREF_YEAR");
            return (Criteria) this;
        }

        public Criteria andSAPREF_YEARBetween(String value1, String value2) {
            addCriterion("SAPREF_YEAR between", value1, value2, "SAPREF_YEAR");
            return (Criteria) this;
        }

        public Criteria andSAPREF_YEARNotBetween(String value1, String value2) {
            addCriterion("SAPREF_YEAR not between", value1, value2, "SAPREF_YEAR");
            return (Criteria) this;
        }

        public Criteria andPOSTBatchIDIsNull() {
            addCriterion("POSTBatchID is null");
            return (Criteria) this;
        }

        public Criteria andPOSTBatchIDIsNotNull() {
            addCriterion("POSTBatchID is not null");
            return (Criteria) this;
        }

        public Criteria andPOSTBatchIDEqualTo(String value) {
            addCriterion("POSTBatchID =", value, "POSTBatchID");
            return (Criteria) this;
        }

        public Criteria andPOSTBatchIDNotEqualTo(String value) {
            addCriterion("POSTBatchID <>", value, "POSTBatchID");
            return (Criteria) this;
        }

        public Criteria andPOSTBatchIDGreaterThan(String value) {
            addCriterion("POSTBatchID >", value, "POSTBatchID");
            return (Criteria) this;
        }

        public Criteria andPOSTBatchIDGreaterThanOrEqualTo(String value) {
            addCriterion("POSTBatchID >=", value, "POSTBatchID");
            return (Criteria) this;
        }

        public Criteria andPOSTBatchIDLessThan(String value) {
            addCriterion("POSTBatchID <", value, "POSTBatchID");
            return (Criteria) this;
        }

        public Criteria andPOSTBatchIDLessThanOrEqualTo(String value) {
            addCriterion("POSTBatchID <=", value, "POSTBatchID");
            return (Criteria) this;
        }

        public Criteria andPOSTBatchIDLike(String value) {
            addCriterion("POSTBatchID like", value, "POSTBatchID");
            return (Criteria) this;
        }

        public Criteria andPOSTBatchIDNotLike(String value) {
            addCriterion("POSTBatchID not like", value, "POSTBatchID");
            return (Criteria) this;
        }

        public Criteria andPOSTBatchIDIn(List<String> values) {
            addCriterion("POSTBatchID in", values, "POSTBatchID");
            return (Criteria) this;
        }

        public Criteria andPOSTBatchIDNotIn(List<String> values) {
            addCriterion("POSTBatchID not in", values, "POSTBatchID");
            return (Criteria) this;
        }

        public Criteria andPOSTBatchIDBetween(String value1, String value2) {
            addCriterion("POSTBatchID between", value1, value2, "POSTBatchID");
            return (Criteria) this;
        }

        public Criteria andPOSTBatchIDNotBetween(String value1, String value2) {
            addCriterion("POSTBatchID not between", value1, value2, "POSTBatchID");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xTend_MaterialTxnLog
     *
     * @mbggenerated do_not_delete_during_merge Mon Dec 19 14:31:30 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xTend_MaterialTxnLog
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}