package com.ht.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TransactionSummaryExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xTend_MaterialTransactionsSummary
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xTend_MaterialTransactionsSummary
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xTend_MaterialTransactionsSummary
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTransactionsSummary
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public TransactionSummaryExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTransactionsSummary
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTransactionsSummary
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTransactionsSummary
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTransactionsSummary
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTransactionsSummary
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTransactionsSummary
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTransactionsSummary
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTransactionsSummary
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTransactionsSummary
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTransactionsSummary
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xTend_MaterialTransactionsSummary
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBatchIdIsNull() {
            addCriterion("BatchId is null");
            return (Criteria) this;
        }

        public Criteria andBatchIdIsNotNull() {
            addCriterion("BatchId is not null");
            return (Criteria) this;
        }

        public Criteria andBatchIdEqualTo(String value) {
            addCriterion("BatchId =", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdNotEqualTo(String value) {
            addCriterion("BatchId <>", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdGreaterThan(String value) {
            addCriterion("BatchId >", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdGreaterThanOrEqualTo(String value) {
            addCriterion("BatchId >=", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdLessThan(String value) {
            addCriterion("BatchId <", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdLessThanOrEqualTo(String value) {
            addCriterion("BatchId <=", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdLike(String value) {
            addCriterion("BatchId like", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdNotLike(String value) {
            addCriterion("BatchId not like", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdIn(List<String> values) {
            addCriterion("BatchId in", values, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdNotIn(List<String> values) {
            addCriterion("BatchId not in", values, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdBetween(String value1, String value2) {
            addCriterion("BatchId between", value1, value2, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdNotBetween(String value1, String value2) {
            addCriterion("BatchId not between", value1, value2, "batchId");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNull() {
            addCriterion("ItemId is null");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNotNull() {
            addCriterion("ItemId is not null");
            return (Criteria) this;
        }

        public Criteria andItemIdEqualTo(Integer value) {
            addCriterion("ItemId =", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotEqualTo(Integer value) {
            addCriterion("ItemId <>", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThan(Integer value) {
            addCriterion("ItemId >", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ItemId >=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThan(Integer value) {
            addCriterion("ItemId <", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThanOrEqualTo(Integer value) {
            addCriterion("ItemId <=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdIn(List<Integer> values) {
            addCriterion("ItemId in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotIn(List<Integer> values) {
            addCriterion("ItemId not in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdBetween(Integer value1, Integer value2) {
            addCriterion("ItemId between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ItemId not between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andBatchIsNull() {
            addCriterion("Batch is null");
            return (Criteria) this;
        }

        public Criteria andBatchIsNotNull() {
            addCriterion("Batch is not null");
            return (Criteria) this;
        }

        public Criteria andBatchEqualTo(String value) {
            addCriterion("Batch =", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchNotEqualTo(String value) {
            addCriterion("Batch <>", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchGreaterThan(String value) {
            addCriterion("Batch >", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchGreaterThanOrEqualTo(String value) {
            addCriterion("Batch >=", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchLessThan(String value) {
            addCriterion("Batch <", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchLessThanOrEqualTo(String value) {
            addCriterion("Batch <=", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchLike(String value) {
            addCriterion("Batch like", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchNotLike(String value) {
            addCriterion("Batch not like", value, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchIn(List<String> values) {
            addCriterion("Batch in", values, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchNotIn(List<String> values) {
            addCriterion("Batch not in", values, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchBetween(String value1, String value2) {
            addCriterion("Batch between", value1, value2, "batch");
            return (Criteria) this;
        }

        public Criteria andBatchNotBetween(String value1, String value2) {
            addCriterion("Batch not between", value1, value2, "batch");
            return (Criteria) this;
        }

        public Criteria andPartNumberIsNull() {
            addCriterion("PartNumber is null");
            return (Criteria) this;
        }

        public Criteria andPartNumberIsNotNull() {
            addCriterion("PartNumber is not null");
            return (Criteria) this;
        }

        public Criteria andPartNumberEqualTo(String value) {
            addCriterion("PartNumber =", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberNotEqualTo(String value) {
            addCriterion("PartNumber <>", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberGreaterThan(String value) {
            addCriterion("PartNumber >", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberGreaterThanOrEqualTo(String value) {
            addCriterion("PartNumber >=", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberLessThan(String value) {
            addCriterion("PartNumber <", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberLessThanOrEqualTo(String value) {
            addCriterion("PartNumber <=", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberLike(String value) {
            addCriterion("PartNumber like", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberNotLike(String value) {
            addCriterion("PartNumber not like", value, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberIn(List<String> values) {
            addCriterion("PartNumber in", values, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberNotIn(List<String> values) {
            addCriterion("PartNumber not in", values, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberBetween(String value1, String value2) {
            addCriterion("PartNumber between", value1, value2, "partNumber");
            return (Criteria) this;
        }

        public Criteria andPartNumberNotBetween(String value1, String value2) {
            addCriterion("PartNumber not between", value1, value2, "partNumber");
            return (Criteria) this;
        }

        public Criteria andFromStockIsNull() {
            addCriterion("FromStock is null");
            return (Criteria) this;
        }

        public Criteria andFromStockIsNotNull() {
            addCriterion("FromStock is not null");
            return (Criteria) this;
        }

        public Criteria andFromStockEqualTo(String value) {
            addCriterion("FromStock =", value, "fromStock");
            return (Criteria) this;
        }

        public Criteria andFromStockNotEqualTo(String value) {
            addCriterion("FromStock <>", value, "fromStock");
            return (Criteria) this;
        }

        public Criteria andFromStockGreaterThan(String value) {
            addCriterion("FromStock >", value, "fromStock");
            return (Criteria) this;
        }

        public Criteria andFromStockGreaterThanOrEqualTo(String value) {
            addCriterion("FromStock >=", value, "fromStock");
            return (Criteria) this;
        }

        public Criteria andFromStockLessThan(String value) {
            addCriterion("FromStock <", value, "fromStock");
            return (Criteria) this;
        }

        public Criteria andFromStockLessThanOrEqualTo(String value) {
            addCriterion("FromStock <=", value, "fromStock");
            return (Criteria) this;
        }

        public Criteria andFromStockLike(String value) {
            addCriterion("FromStock like", value, "fromStock");
            return (Criteria) this;
        }

        public Criteria andFromStockNotLike(String value) {
            addCriterion("FromStock not like", value, "fromStock");
            return (Criteria) this;
        }

        public Criteria andFromStockIn(List<String> values) {
            addCriterion("FromStock in", values, "fromStock");
            return (Criteria) this;
        }

        public Criteria andFromStockNotIn(List<String> values) {
            addCriterion("FromStock not in", values, "fromStock");
            return (Criteria) this;
        }

        public Criteria andFromStockBetween(String value1, String value2) {
            addCriterion("FromStock between", value1, value2, "fromStock");
            return (Criteria) this;
        }

        public Criteria andFromStockNotBetween(String value1, String value2) {
            addCriterion("FromStock not between", value1, value2, "fromStock");
            return (Criteria) this;
        }

        public Criteria andToStockIsNull() {
            addCriterion("ToStock is null");
            return (Criteria) this;
        }

        public Criteria andToStockIsNotNull() {
            addCriterion("ToStock is not null");
            return (Criteria) this;
        }

        public Criteria andToStockEqualTo(String value) {
            addCriterion("ToStock =", value, "toStock");
            return (Criteria) this;
        }

        public Criteria andToStockNotEqualTo(String value) {
            addCriterion("ToStock <>", value, "toStock");
            return (Criteria) this;
        }

        public Criteria andToStockGreaterThan(String value) {
            addCriterion("ToStock >", value, "toStock");
            return (Criteria) this;
        }

        public Criteria andToStockGreaterThanOrEqualTo(String value) {
            addCriterion("ToStock >=", value, "toStock");
            return (Criteria) this;
        }

        public Criteria andToStockLessThan(String value) {
            addCriterion("ToStock <", value, "toStock");
            return (Criteria) this;
        }

        public Criteria andToStockLessThanOrEqualTo(String value) {
            addCriterion("ToStock <=", value, "toStock");
            return (Criteria) this;
        }

        public Criteria andToStockLike(String value) {
            addCriterion("ToStock like", value, "toStock");
            return (Criteria) this;
        }

        public Criteria andToStockNotLike(String value) {
            addCriterion("ToStock not like", value, "toStock");
            return (Criteria) this;
        }

        public Criteria andToStockIn(List<String> values) {
            addCriterion("ToStock in", values, "toStock");
            return (Criteria) this;
        }

        public Criteria andToStockNotIn(List<String> values) {
            addCriterion("ToStock not in", values, "toStock");
            return (Criteria) this;
        }

        public Criteria andToStockBetween(String value1, String value2) {
            addCriterion("ToStock between", value1, value2, "toStock");
            return (Criteria) this;
        }

        public Criteria andToStockNotBetween(String value1, String value2) {
            addCriterion("ToStock not between", value1, value2, "toStock");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNull() {
            addCriterion("Quantity is null");
            return (Criteria) this;
        }

        public Criteria andQuantityIsNotNull() {
            addCriterion("Quantity is not null");
            return (Criteria) this;
        }

        public Criteria andQuantityEqualTo(Double value) {
            addCriterion("Quantity =", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotEqualTo(Double value) {
            addCriterion("Quantity <>", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThan(Double value) {
            addCriterion("Quantity >", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityGreaterThanOrEqualTo(Double value) {
            addCriterion("Quantity >=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThan(Double value) {
            addCriterion("Quantity <", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityLessThanOrEqualTo(Double value) {
            addCriterion("Quantity <=", value, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityIn(List<Double> values) {
            addCriterion("Quantity in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotIn(List<Double> values) {
            addCriterion("Quantity not in", values, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityBetween(Double value1, Double value2) {
            addCriterion("Quantity between", value1, value2, "quantity");
            return (Criteria) this;
        }

        public Criteria andQuantityNotBetween(Double value1, Double value2) {
            addCriterion("Quantity not between", value1, value2, "quantity");
            return (Criteria) this;
        }

        public Criteria andUOMIsNull() {
            addCriterion("UOM is null");
            return (Criteria) this;
        }

        public Criteria andUOMIsNotNull() {
            addCriterion("UOM is not null");
            return (Criteria) this;
        }

        public Criteria andUOMEqualTo(String value) {
            addCriterion("UOM =", value, "UOM");
            return (Criteria) this;
        }

        public Criteria andUOMNotEqualTo(String value) {
            addCriterion("UOM <>", value, "UOM");
            return (Criteria) this;
        }

        public Criteria andUOMGreaterThan(String value) {
            addCriterion("UOM >", value, "UOM");
            return (Criteria) this;
        }

        public Criteria andUOMGreaterThanOrEqualTo(String value) {
            addCriterion("UOM >=", value, "UOM");
            return (Criteria) this;
        }

        public Criteria andUOMLessThan(String value) {
            addCriterion("UOM <", value, "UOM");
            return (Criteria) this;
        }

        public Criteria andUOMLessThanOrEqualTo(String value) {
            addCriterion("UOM <=", value, "UOM");
            return (Criteria) this;
        }

        public Criteria andUOMLike(String value) {
            addCriterion("UOM like", value, "UOM");
            return (Criteria) this;
        }

        public Criteria andUOMNotLike(String value) {
            addCriterion("UOM not like", value, "UOM");
            return (Criteria) this;
        }

        public Criteria andUOMIn(List<String> values) {
            addCriterion("UOM in", values, "UOM");
            return (Criteria) this;
        }

        public Criteria andUOMNotIn(List<String> values) {
            addCriterion("UOM not in", values, "UOM");
            return (Criteria) this;
        }

        public Criteria andUOMBetween(String value1, String value2) {
            addCriterion("UOM between", value1, value2, "UOM");
            return (Criteria) this;
        }

        public Criteria andUOMNotBetween(String value1, String value2) {
            addCriterion("UOM not between", value1, value2, "UOM");
            return (Criteria) this;
        }

        public Criteria andTransactionUserIsNull() {
            addCriterion("TransactionUser is null");
            return (Criteria) this;
        }

        public Criteria andTransactionUserIsNotNull() {
            addCriterion("TransactionUser is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionUserEqualTo(String value) {
            addCriterion("TransactionUser =", value, "transactionUser");
            return (Criteria) this;
        }

        public Criteria andTransactionUserNotEqualTo(String value) {
            addCriterion("TransactionUser <>", value, "transactionUser");
            return (Criteria) this;
        }

        public Criteria andTransactionUserGreaterThan(String value) {
            addCriterion("TransactionUser >", value, "transactionUser");
            return (Criteria) this;
        }

        public Criteria andTransactionUserGreaterThanOrEqualTo(String value) {
            addCriterion("TransactionUser >=", value, "transactionUser");
            return (Criteria) this;
        }

        public Criteria andTransactionUserLessThan(String value) {
            addCriterion("TransactionUser <", value, "transactionUser");
            return (Criteria) this;
        }

        public Criteria andTransactionUserLessThanOrEqualTo(String value) {
            addCriterion("TransactionUser <=", value, "transactionUser");
            return (Criteria) this;
        }

        public Criteria andTransactionUserLike(String value) {
            addCriterion("TransactionUser like", value, "transactionUser");
            return (Criteria) this;
        }

        public Criteria andTransactionUserNotLike(String value) {
            addCriterion("TransactionUser not like", value, "transactionUser");
            return (Criteria) this;
        }

        public Criteria andTransactionUserIn(List<String> values) {
            addCriterion("TransactionUser in", values, "transactionUser");
            return (Criteria) this;
        }

        public Criteria andTransactionUserNotIn(List<String> values) {
            addCriterion("TransactionUser not in", values, "transactionUser");
            return (Criteria) this;
        }

        public Criteria andTransactionUserBetween(String value1, String value2) {
            addCriterion("TransactionUser between", value1, value2, "transactionUser");
            return (Criteria) this;
        }

        public Criteria andTransactionUserNotBetween(String value1, String value2) {
            addCriterion("TransactionUser not between", value1, value2, "transactionUser");
            return (Criteria) this;
        }

        public Criteria andTransactionTimeIsNull() {
            addCriterion("TransactionTime is null");
            return (Criteria) this;
        }

        public Criteria andTransactionTimeIsNotNull() {
            addCriterion("TransactionTime is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionTimeEqualTo(Date value) {
            addCriterion("TransactionTime =", value, "transactionTime");
            return (Criteria) this;
        }

        public Criteria andTransactionTimeNotEqualTo(Date value) {
            addCriterion("TransactionTime <>", value, "transactionTime");
            return (Criteria) this;
        }

        public Criteria andTransactionTimeGreaterThan(Date value) {
            addCriterion("TransactionTime >", value, "transactionTime");
            return (Criteria) this;
        }

        public Criteria andTransactionTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("TransactionTime >=", value, "transactionTime");
            return (Criteria) this;
        }

        public Criteria andTransactionTimeLessThan(Date value) {
            addCriterion("TransactionTime <", value, "transactionTime");
            return (Criteria) this;
        }

        public Criteria andTransactionTimeLessThanOrEqualTo(Date value) {
            addCriterion("TransactionTime <=", value, "transactionTime");
            return (Criteria) this;
        }

        public Criteria andTransactionTimeIn(List<Date> values) {
            addCriterion("TransactionTime in", values, "transactionTime");
            return (Criteria) this;
        }

        public Criteria andTransactionTimeNotIn(List<Date> values) {
            addCriterion("TransactionTime not in", values, "transactionTime");
            return (Criteria) this;
        }

        public Criteria andTransactionTimeBetween(Date value1, Date value2) {
            addCriterion("TransactionTime between", value1, value2, "transactionTime");
            return (Criteria) this;
        }

        public Criteria andTransactionTimeNotBetween(Date value1, Date value2) {
            addCriterion("TransactionTime not between", value1, value2, "transactionTime");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeIsNull() {
            addCriterion("TransactionType is null");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeIsNotNull() {
            addCriterion("TransactionType is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeEqualTo(String value) {
            addCriterion("TransactionType =", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeNotEqualTo(String value) {
            addCriterion("TransactionType <>", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeGreaterThan(String value) {
            addCriterion("TransactionType >", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeGreaterThanOrEqualTo(String value) {
            addCriterion("TransactionType >=", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeLessThan(String value) {
            addCriterion("TransactionType <", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeLessThanOrEqualTo(String value) {
            addCriterion("TransactionType <=", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeLike(String value) {
            addCriterion("TransactionType like", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeNotLike(String value) {
            addCriterion("TransactionType not like", value, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeIn(List<String> values) {
            addCriterion("TransactionType in", values, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeNotIn(List<String> values) {
            addCriterion("TransactionType not in", values, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeBetween(String value1, String value2) {
            addCriterion("TransactionType between", value1, value2, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionTypeNotBetween(String value1, String value2) {
            addCriterion("TransactionType not between", value1, value2, "transactionType");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonIsNull() {
            addCriterion("TransactionReason is null");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonIsNotNull() {
            addCriterion("TransactionReason is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonEqualTo(String value) {
            addCriterion("TransactionReason =", value, "transactionReason");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonNotEqualTo(String value) {
            addCriterion("TransactionReason <>", value, "transactionReason");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonGreaterThan(String value) {
            addCriterion("TransactionReason >", value, "transactionReason");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonGreaterThanOrEqualTo(String value) {
            addCriterion("TransactionReason >=", value, "transactionReason");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonLessThan(String value) {
            addCriterion("TransactionReason <", value, "transactionReason");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonLessThanOrEqualTo(String value) {
            addCriterion("TransactionReason <=", value, "transactionReason");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonLike(String value) {
            addCriterion("TransactionReason like", value, "transactionReason");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonNotLike(String value) {
            addCriterion("TransactionReason not like", value, "transactionReason");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonIn(List<String> values) {
            addCriterion("TransactionReason in", values, "transactionReason");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonNotIn(List<String> values) {
            addCriterion("TransactionReason not in", values, "transactionReason");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonBetween(String value1, String value2) {
            addCriterion("TransactionReason between", value1, value2, "transactionReason");
            return (Criteria) this;
        }

        public Criteria andTransactionReasonNotBetween(String value1, String value2) {
            addCriterion("TransactionReason not between", value1, value2, "transactionReason");
            return (Criteria) this;
        }

        public Criteria andTransactionResultIsNull() {
            addCriterion("TransactionResult is null");
            return (Criteria) this;
        }

        public Criteria andTransactionResultIsNotNull() {
            addCriterion("TransactionResult is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionResultEqualTo(Integer value) {
            addCriterion("TransactionResult =", value, "transactionResult");
            return (Criteria) this;
        }

        public Criteria andTransactionResultNotEqualTo(Integer value) {
            addCriterion("TransactionResult <>", value, "transactionResult");
            return (Criteria) this;
        }

        public Criteria andTransactionResultGreaterThan(Integer value) {
            addCriterion("TransactionResult >", value, "transactionResult");
            return (Criteria) this;
        }

        public Criteria andTransactionResultGreaterThanOrEqualTo(Integer value) {
            addCriterion("TransactionResult >=", value, "transactionResult");
            return (Criteria) this;
        }

        public Criteria andTransactionResultLessThan(Integer value) {
            addCriterion("TransactionResult <", value, "transactionResult");
            return (Criteria) this;
        }

        public Criteria andTransactionResultLessThanOrEqualTo(Integer value) {
            addCriterion("TransactionResult <=", value, "transactionResult");
            return (Criteria) this;
        }

        public Criteria andTransactionResultIn(List<Integer> values) {
            addCriterion("TransactionResult in", values, "transactionResult");
            return (Criteria) this;
        }

        public Criteria andTransactionResultNotIn(List<Integer> values) {
            addCriterion("TransactionResult not in", values, "transactionResult");
            return (Criteria) this;
        }

        public Criteria andTransactionResultBetween(Integer value1, Integer value2) {
            addCriterion("TransactionResult between", value1, value2, "transactionResult");
            return (Criteria) this;
        }

        public Criteria andTransactionResultNotBetween(Integer value1, Integer value2) {
            addCriterion("TransactionResult not between", value1, value2, "transactionResult");
            return (Criteria) this;
        }

        public Criteria andRetryCountIsNull() {
            addCriterion("RetryCount is null");
            return (Criteria) this;
        }

        public Criteria andRetryCountIsNotNull() {
            addCriterion("RetryCount is not null");
            return (Criteria) this;
        }

        public Criteria andRetryCountEqualTo(Integer value) {
            addCriterion("RetryCount =", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountNotEqualTo(Integer value) {
            addCriterion("RetryCount <>", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountGreaterThan(Integer value) {
            addCriterion("RetryCount >", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("RetryCount >=", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountLessThan(Integer value) {
            addCriterion("RetryCount <", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountLessThanOrEqualTo(Integer value) {
            addCriterion("RetryCount <=", value, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountIn(List<Integer> values) {
            addCriterion("RetryCount in", values, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountNotIn(List<Integer> values) {
            addCriterion("RetryCount not in", values, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountBetween(Integer value1, Integer value2) {
            addCriterion("RetryCount between", value1, value2, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRetryCountNotBetween(Integer value1, Integer value2) {
            addCriterion("RetryCount not between", value1, value2, "retryCount");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDIsNull() {
            addCriterion("RFCTemplateID is null");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDIsNotNull() {
            addCriterion("RFCTemplateID is not null");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDEqualTo(String value) {
            addCriterion("RFCTemplateID =", value, "RFCTemplateID");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDNotEqualTo(String value) {
            addCriterion("RFCTemplateID <>", value, "RFCTemplateID");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDGreaterThan(String value) {
            addCriterion("RFCTemplateID >", value, "RFCTemplateID");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDGreaterThanOrEqualTo(String value) {
            addCriterion("RFCTemplateID >=", value, "RFCTemplateID");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDLessThan(String value) {
            addCriterion("RFCTemplateID <", value, "RFCTemplateID");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDLessThanOrEqualTo(String value) {
            addCriterion("RFCTemplateID <=", value, "RFCTemplateID");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDLike(String value) {
            addCriterion("RFCTemplateID like", value, "RFCTemplateID");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDNotLike(String value) {
            addCriterion("RFCTemplateID not like", value, "RFCTemplateID");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDIn(List<String> values) {
            addCriterion("RFCTemplateID in", values, "RFCTemplateID");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDNotIn(List<String> values) {
            addCriterion("RFCTemplateID not in", values, "RFCTemplateID");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDBetween(String value1, String value2) {
            addCriterion("RFCTemplateID between", value1, value2, "RFCTemplateID");
            return (Criteria) this;
        }

        public Criteria andRFCTemplateIDNotBetween(String value1, String value2) {
            addCriterion("RFCTemplateID not between", value1, value2, "RFCTemplateID");
            return (Criteria) this;
        }

        public Criteria andRefDocNoIsNull() {
            addCriterion("RefDocNo is null");
            return (Criteria) this;
        }

        public Criteria andRefDocNoIsNotNull() {
            addCriterion("RefDocNo is not null");
            return (Criteria) this;
        }

        public Criteria andRefDocNoEqualTo(String value) {
            addCriterion("RefDocNo =", value, "refDocNo");
            return (Criteria) this;
        }

        public Criteria andRefDocNoNotEqualTo(String value) {
            addCriterion("RefDocNo <>", value, "refDocNo");
            return (Criteria) this;
        }

        public Criteria andRefDocNoGreaterThan(String value) {
            addCriterion("RefDocNo >", value, "refDocNo");
            return (Criteria) this;
        }

        public Criteria andRefDocNoGreaterThanOrEqualTo(String value) {
            addCriterion("RefDocNo >=", value, "refDocNo");
            return (Criteria) this;
        }

        public Criteria andRefDocNoLessThan(String value) {
            addCriterion("RefDocNo <", value, "refDocNo");
            return (Criteria) this;
        }

        public Criteria andRefDocNoLessThanOrEqualTo(String value) {
            addCriterion("RefDocNo <=", value, "refDocNo");
            return (Criteria) this;
        }

        public Criteria andRefDocNoLike(String value) {
            addCriterion("RefDocNo like", value, "refDocNo");
            return (Criteria) this;
        }

        public Criteria andRefDocNoNotLike(String value) {
            addCriterion("RefDocNo not like", value, "refDocNo");
            return (Criteria) this;
        }

        public Criteria andRefDocNoIn(List<String> values) {
            addCriterion("RefDocNo in", values, "refDocNo");
            return (Criteria) this;
        }

        public Criteria andRefDocNoNotIn(List<String> values) {
            addCriterion("RefDocNo not in", values, "refDocNo");
            return (Criteria) this;
        }

        public Criteria andRefDocNoBetween(String value1, String value2) {
            addCriterion("RefDocNo between", value1, value2, "refDocNo");
            return (Criteria) this;
        }

        public Criteria andRefDocNoNotBetween(String value1, String value2) {
            addCriterion("RefDocNo not between", value1, value2, "refDocNo");
            return (Criteria) this;
        }

        public Criteria andDocHeaderIsNull() {
            addCriterion("DocHeader is null");
            return (Criteria) this;
        }

        public Criteria andDocHeaderIsNotNull() {
            addCriterion("DocHeader is not null");
            return (Criteria) this;
        }

        public Criteria andDocHeaderEqualTo(String value) {
            addCriterion("DocHeader =", value, "docHeader");
            return (Criteria) this;
        }

        public Criteria andDocHeaderNotEqualTo(String value) {
            addCriterion("DocHeader <>", value, "docHeader");
            return (Criteria) this;
        }

        public Criteria andDocHeaderGreaterThan(String value) {
            addCriterion("DocHeader >", value, "docHeader");
            return (Criteria) this;
        }

        public Criteria andDocHeaderGreaterThanOrEqualTo(String value) {
            addCriterion("DocHeader >=", value, "docHeader");
            return (Criteria) this;
        }

        public Criteria andDocHeaderLessThan(String value) {
            addCriterion("DocHeader <", value, "docHeader");
            return (Criteria) this;
        }

        public Criteria andDocHeaderLessThanOrEqualTo(String value) {
            addCriterion("DocHeader <=", value, "docHeader");
            return (Criteria) this;
        }

        public Criteria andDocHeaderLike(String value) {
            addCriterion("DocHeader like", value, "docHeader");
            return (Criteria) this;
        }

        public Criteria andDocHeaderNotLike(String value) {
            addCriterion("DocHeader not like", value, "docHeader");
            return (Criteria) this;
        }

        public Criteria andDocHeaderIn(List<String> values) {
            addCriterion("DocHeader in", values, "docHeader");
            return (Criteria) this;
        }

        public Criteria andDocHeaderNotIn(List<String> values) {
            addCriterion("DocHeader not in", values, "docHeader");
            return (Criteria) this;
        }

        public Criteria andDocHeaderBetween(String value1, String value2) {
            addCriterion("DocHeader between", value1, value2, "docHeader");
            return (Criteria) this;
        }

        public Criteria andDocHeaderNotBetween(String value1, String value2) {
            addCriterion("DocHeader not between", value1, value2, "docHeader");
            return (Criteria) this;
        }

        public Criteria andPlantIsNull() {
            addCriterion("Plant is null");
            return (Criteria) this;
        }

        public Criteria andPlantIsNotNull() {
            addCriterion("Plant is not null");
            return (Criteria) this;
        }

        public Criteria andPlantEqualTo(String value) {
            addCriterion("Plant =", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantNotEqualTo(String value) {
            addCriterion("Plant <>", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantGreaterThan(String value) {
            addCriterion("Plant >", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantGreaterThanOrEqualTo(String value) {
            addCriterion("Plant >=", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantLessThan(String value) {
            addCriterion("Plant <", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantLessThanOrEqualTo(String value) {
            addCriterion("Plant <=", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantLike(String value) {
            addCriterion("Plant like", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantNotLike(String value) {
            addCriterion("Plant not like", value, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantIn(List<String> values) {
            addCriterion("Plant in", values, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantNotIn(List<String> values) {
            addCriterion("Plant not in", values, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantBetween(String value1, String value2) {
            addCriterion("Plant between", value1, value2, "plant");
            return (Criteria) this;
        }

        public Criteria andPlantNotBetween(String value1, String value2) {
            addCriterion("Plant not between", value1, value2, "plant");
            return (Criteria) this;
        }

        public Criteria andVendorIsNull() {
            addCriterion("Vendor is null");
            return (Criteria) this;
        }

        public Criteria andVendorIsNotNull() {
            addCriterion("Vendor is not null");
            return (Criteria) this;
        }

        public Criteria andVendorEqualTo(String value) {
            addCriterion("Vendor =", value, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorNotEqualTo(String value) {
            addCriterion("Vendor <>", value, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorGreaterThan(String value) {
            addCriterion("Vendor >", value, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorGreaterThanOrEqualTo(String value) {
            addCriterion("Vendor >=", value, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorLessThan(String value) {
            addCriterion("Vendor <", value, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorLessThanOrEqualTo(String value) {
            addCriterion("Vendor <=", value, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorLike(String value) {
            addCriterion("Vendor like", value, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorNotLike(String value) {
            addCriterion("Vendor not like", value, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorIn(List<String> values) {
            addCriterion("Vendor in", values, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorNotIn(List<String> values) {
            addCriterion("Vendor not in", values, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorBetween(String value1, String value2) {
            addCriterion("Vendor between", value1, value2, "vendor");
            return (Criteria) this;
        }

        public Criteria andVendorNotBetween(String value1, String value2) {
            addCriterion("Vendor not between", value1, value2, "vendor");
            return (Criteria) this;
        }

        public Criteria andSpecialStockIsNull() {
            addCriterion("SpecialStock is null");
            return (Criteria) this;
        }

        public Criteria andSpecialStockIsNotNull() {
            addCriterion("SpecialStock is not null");
            return (Criteria) this;
        }

        public Criteria andSpecialStockEqualTo(String value) {
            addCriterion("SpecialStock =", value, "specialStock");
            return (Criteria) this;
        }

        public Criteria andSpecialStockNotEqualTo(String value) {
            addCriterion("SpecialStock <>", value, "specialStock");
            return (Criteria) this;
        }

        public Criteria andSpecialStockGreaterThan(String value) {
            addCriterion("SpecialStock >", value, "specialStock");
            return (Criteria) this;
        }

        public Criteria andSpecialStockGreaterThanOrEqualTo(String value) {
            addCriterion("SpecialStock >=", value, "specialStock");
            return (Criteria) this;
        }

        public Criteria andSpecialStockLessThan(String value) {
            addCriterion("SpecialStock <", value, "specialStock");
            return (Criteria) this;
        }

        public Criteria andSpecialStockLessThanOrEqualTo(String value) {
            addCriterion("SpecialStock <=", value, "specialStock");
            return (Criteria) this;
        }

        public Criteria andSpecialStockLike(String value) {
            addCriterion("SpecialStock like", value, "specialStock");
            return (Criteria) this;
        }

        public Criteria andSpecialStockNotLike(String value) {
            addCriterion("SpecialStock not like", value, "specialStock");
            return (Criteria) this;
        }

        public Criteria andSpecialStockIn(List<String> values) {
            addCriterion("SpecialStock in", values, "specialStock");
            return (Criteria) this;
        }

        public Criteria andSpecialStockNotIn(List<String> values) {
            addCriterion("SpecialStock not in", values, "specialStock");
            return (Criteria) this;
        }

        public Criteria andSpecialStockBetween(String value1, String value2) {
            addCriterion("SpecialStock between", value1, value2, "specialStock");
            return (Criteria) this;
        }

        public Criteria andSpecialStockNotBetween(String value1, String value2) {
            addCriterion("SpecialStock not between", value1, value2, "specialStock");
            return (Criteria) this;
        }

        public Criteria andI_PRUEFLOSIsNull() {
            addCriterion("I_PRUEFLOS is null");
            return (Criteria) this;
        }

        public Criteria andI_PRUEFLOSIsNotNull() {
            addCriterion("I_PRUEFLOS is not null");
            return (Criteria) this;
        }

        public Criteria andI_PRUEFLOSEqualTo(String value) {
            addCriterion("I_PRUEFLOS =", value, "i_PRUEFLOS");
            return (Criteria) this;
        }

        public Criteria andI_PRUEFLOSNotEqualTo(String value) {
            addCriterion("I_PRUEFLOS <>", value, "i_PRUEFLOS");
            return (Criteria) this;
        }

        public Criteria andI_PRUEFLOSGreaterThan(String value) {
            addCriterion("I_PRUEFLOS >", value, "i_PRUEFLOS");
            return (Criteria) this;
        }

        public Criteria andI_PRUEFLOSGreaterThanOrEqualTo(String value) {
            addCriterion("I_PRUEFLOS >=", value, "i_PRUEFLOS");
            return (Criteria) this;
        }

        public Criteria andI_PRUEFLOSLessThan(String value) {
            addCriterion("I_PRUEFLOS <", value, "i_PRUEFLOS");
            return (Criteria) this;
        }

        public Criteria andI_PRUEFLOSLessThanOrEqualTo(String value) {
            addCriterion("I_PRUEFLOS <=", value, "i_PRUEFLOS");
            return (Criteria) this;
        }

        public Criteria andI_PRUEFLOSLike(String value) {
            addCriterion("I_PRUEFLOS like", value, "i_PRUEFLOS");
            return (Criteria) this;
        }

        public Criteria andI_PRUEFLOSNotLike(String value) {
            addCriterion("I_PRUEFLOS not like", value, "i_PRUEFLOS");
            return (Criteria) this;
        }

        public Criteria andI_PRUEFLOSIn(List<String> values) {
            addCriterion("I_PRUEFLOS in", values, "i_PRUEFLOS");
            return (Criteria) this;
        }

        public Criteria andI_PRUEFLOSNotIn(List<String> values) {
            addCriterion("I_PRUEFLOS not in", values, "i_PRUEFLOS");
            return (Criteria) this;
        }

        public Criteria andI_PRUEFLOSBetween(String value1, String value2) {
            addCriterion("I_PRUEFLOS between", value1, value2, "i_PRUEFLOS");
            return (Criteria) this;
        }

        public Criteria andI_PRUEFLOSNotBetween(String value1, String value2) {
            addCriterion("I_PRUEFLOS not between", value1, value2, "i_PRUEFLOS");
            return (Criteria) this;
        }

        public Criteria andI_VCODEIsNull() {
            addCriterion("I_VCODE is null");
            return (Criteria) this;
        }

        public Criteria andI_VCODEIsNotNull() {
            addCriterion("I_VCODE is not null");
            return (Criteria) this;
        }

        public Criteria andI_VCODEEqualTo(String value) {
            addCriterion("I_VCODE =", value, "i_VCODE");
            return (Criteria) this;
        }

        public Criteria andI_VCODENotEqualTo(String value) {
            addCriterion("I_VCODE <>", value, "i_VCODE");
            return (Criteria) this;
        }

        public Criteria andI_VCODEGreaterThan(String value) {
            addCriterion("I_VCODE >", value, "i_VCODE");
            return (Criteria) this;
        }

        public Criteria andI_VCODEGreaterThanOrEqualTo(String value) {
            addCriterion("I_VCODE >=", value, "i_VCODE");
            return (Criteria) this;
        }

        public Criteria andI_VCODELessThan(String value) {
            addCriterion("I_VCODE <", value, "i_VCODE");
            return (Criteria) this;
        }

        public Criteria andI_VCODELessThanOrEqualTo(String value) {
            addCriterion("I_VCODE <=", value, "i_VCODE");
            return (Criteria) this;
        }

        public Criteria andI_VCODELike(String value) {
            addCriterion("I_VCODE like", value, "i_VCODE");
            return (Criteria) this;
        }

        public Criteria andI_VCODENotLike(String value) {
            addCriterion("I_VCODE not like", value, "i_VCODE");
            return (Criteria) this;
        }

        public Criteria andI_VCODEIn(List<String> values) {
            addCriterion("I_VCODE in", values, "i_VCODE");
            return (Criteria) this;
        }

        public Criteria andI_VCODENotIn(List<String> values) {
            addCriterion("I_VCODE not in", values, "i_VCODE");
            return (Criteria) this;
        }

        public Criteria andI_VCODEBetween(String value1, String value2) {
            addCriterion("I_VCODE between", value1, value2, "i_VCODE");
            return (Criteria) this;
        }

        public Criteria andI_VCODENotBetween(String value1, String value2) {
            addCriterion("I_VCODE not between", value1, value2, "i_VCODE");
            return (Criteria) this;
        }

        public Criteria andGR_RCPTIsNull() {
            addCriterion("GR_RCPT is null");
            return (Criteria) this;
        }

        public Criteria andGR_RCPTIsNotNull() {
            addCriterion("GR_RCPT is not null");
            return (Criteria) this;
        }

        public Criteria andGR_RCPTEqualTo(String value) {
            addCriterion("GR_RCPT =", value, "GR_RCPT");
            return (Criteria) this;
        }

        public Criteria andGR_RCPTNotEqualTo(String value) {
            addCriterion("GR_RCPT <>", value, "GR_RCPT");
            return (Criteria) this;
        }

        public Criteria andGR_RCPTGreaterThan(String value) {
            addCriterion("GR_RCPT >", value, "GR_RCPT");
            return (Criteria) this;
        }

        public Criteria andGR_RCPTGreaterThanOrEqualTo(String value) {
            addCriterion("GR_RCPT >=", value, "GR_RCPT");
            return (Criteria) this;
        }

        public Criteria andGR_RCPTLessThan(String value) {
            addCriterion("GR_RCPT <", value, "GR_RCPT");
            return (Criteria) this;
        }

        public Criteria andGR_RCPTLessThanOrEqualTo(String value) {
            addCriterion("GR_RCPT <=", value, "GR_RCPT");
            return (Criteria) this;
        }

        public Criteria andGR_RCPTLike(String value) {
            addCriterion("GR_RCPT like", value, "GR_RCPT");
            return (Criteria) this;
        }

        public Criteria andGR_RCPTNotLike(String value) {
            addCriterion("GR_RCPT not like", value, "GR_RCPT");
            return (Criteria) this;
        }

        public Criteria andGR_RCPTIn(List<String> values) {
            addCriterion("GR_RCPT in", values, "GR_RCPT");
            return (Criteria) this;
        }

        public Criteria andGR_RCPTNotIn(List<String> values) {
            addCriterion("GR_RCPT not in", values, "GR_RCPT");
            return (Criteria) this;
        }

        public Criteria andGR_RCPTBetween(String value1, String value2) {
            addCriterion("GR_RCPT between", value1, value2, "GR_RCPT");
            return (Criteria) this;
        }

        public Criteria andGR_RCPTNotBetween(String value1, String value2) {
            addCriterion("GR_RCPT not between", value1, value2, "GR_RCPT");
            return (Criteria) this;
        }

        public Criteria andCOSTCENTERIsNull() {
            addCriterion("COSTCENTER is null");
            return (Criteria) this;
        }

        public Criteria andCOSTCENTERIsNotNull() {
            addCriterion("COSTCENTER is not null");
            return (Criteria) this;
        }

        public Criteria andCOSTCENTEREqualTo(String value) {
            addCriterion("COSTCENTER =", value, "COSTCENTER");
            return (Criteria) this;
        }

        public Criteria andCOSTCENTERNotEqualTo(String value) {
            addCriterion("COSTCENTER <>", value, "COSTCENTER");
            return (Criteria) this;
        }

        public Criteria andCOSTCENTERGreaterThan(String value) {
            addCriterion("COSTCENTER >", value, "COSTCENTER");
            return (Criteria) this;
        }

        public Criteria andCOSTCENTERGreaterThanOrEqualTo(String value) {
            addCriterion("COSTCENTER >=", value, "COSTCENTER");
            return (Criteria) this;
        }

        public Criteria andCOSTCENTERLessThan(String value) {
            addCriterion("COSTCENTER <", value, "COSTCENTER");
            return (Criteria) this;
        }

        public Criteria andCOSTCENTERLessThanOrEqualTo(String value) {
            addCriterion("COSTCENTER <=", value, "COSTCENTER");
            return (Criteria) this;
        }

        public Criteria andCOSTCENTERLike(String value) {
            addCriterion("COSTCENTER like", value, "COSTCENTER");
            return (Criteria) this;
        }

        public Criteria andCOSTCENTERNotLike(String value) {
            addCriterion("COSTCENTER not like", value, "COSTCENTER");
            return (Criteria) this;
        }

        public Criteria andCOSTCENTERIn(List<String> values) {
            addCriterion("COSTCENTER in", values, "COSTCENTER");
            return (Criteria) this;
        }

        public Criteria andCOSTCENTERNotIn(List<String> values) {
            addCriterion("COSTCENTER not in", values, "COSTCENTER");
            return (Criteria) this;
        }

        public Criteria andCOSTCENTERBetween(String value1, String value2) {
            addCriterion("COSTCENTER between", value1, value2, "COSTCENTER");
            return (Criteria) this;
        }

        public Criteria andCOSTCENTERNotBetween(String value1, String value2) {
            addCriterion("COSTCENTER not between", value1, value2, "COSTCENTER");
            return (Criteria) this;
        }

        public Criteria andIND_PROPOSE_QUANXIsNull() {
            addCriterion("IND_PROPOSE_QUANX is null");
            return (Criteria) this;
        }

        public Criteria andIND_PROPOSE_QUANXIsNotNull() {
            addCriterion("IND_PROPOSE_QUANX is not null");
            return (Criteria) this;
        }

        public Criteria andIND_PROPOSE_QUANXEqualTo(String value) {
            addCriterion("IND_PROPOSE_QUANX =", value, "IND_PROPOSE_QUANX");
            return (Criteria) this;
        }

        public Criteria andIND_PROPOSE_QUANXNotEqualTo(String value) {
            addCriterion("IND_PROPOSE_QUANX <>", value, "IND_PROPOSE_QUANX");
            return (Criteria) this;
        }

        public Criteria andIND_PROPOSE_QUANXGreaterThan(String value) {
            addCriterion("IND_PROPOSE_QUANX >", value, "IND_PROPOSE_QUANX");
            return (Criteria) this;
        }

        public Criteria andIND_PROPOSE_QUANXGreaterThanOrEqualTo(String value) {
            addCriterion("IND_PROPOSE_QUANX >=", value, "IND_PROPOSE_QUANX");
            return (Criteria) this;
        }

        public Criteria andIND_PROPOSE_QUANXLessThan(String value) {
            addCriterion("IND_PROPOSE_QUANX <", value, "IND_PROPOSE_QUANX");
            return (Criteria) this;
        }

        public Criteria andIND_PROPOSE_QUANXLessThanOrEqualTo(String value) {
            addCriterion("IND_PROPOSE_QUANX <=", value, "IND_PROPOSE_QUANX");
            return (Criteria) this;
        }

        public Criteria andIND_PROPOSE_QUANXLike(String value) {
            addCriterion("IND_PROPOSE_QUANX like", value, "IND_PROPOSE_QUANX");
            return (Criteria) this;
        }

        public Criteria andIND_PROPOSE_QUANXNotLike(String value) {
            addCriterion("IND_PROPOSE_QUANX not like", value, "IND_PROPOSE_QUANX");
            return (Criteria) this;
        }

        public Criteria andIND_PROPOSE_QUANXIn(List<String> values) {
            addCriterion("IND_PROPOSE_QUANX in", values, "IND_PROPOSE_QUANX");
            return (Criteria) this;
        }

        public Criteria andIND_PROPOSE_QUANXNotIn(List<String> values) {
            addCriterion("IND_PROPOSE_QUANX not in", values, "IND_PROPOSE_QUANX");
            return (Criteria) this;
        }

        public Criteria andIND_PROPOSE_QUANXBetween(String value1, String value2) {
            addCriterion("IND_PROPOSE_QUANX between", value1, value2, "IND_PROPOSE_QUANX");
            return (Criteria) this;
        }

        public Criteria andIND_PROPOSE_QUANXNotBetween(String value1, String value2) {
            addCriterion("IND_PROPOSE_QUANX not between", value1, value2, "IND_PROPOSE_QUANX");
            return (Criteria) this;
        }

        public Criteria andMOVE_MATIsNull() {
            addCriterion("MOVE_MAT is null");
            return (Criteria) this;
        }

        public Criteria andMOVE_MATIsNotNull() {
            addCriterion("MOVE_MAT is not null");
            return (Criteria) this;
        }

        public Criteria andMOVE_MATEqualTo(String value) {
            addCriterion("MOVE_MAT =", value, "MOVE_MAT");
            return (Criteria) this;
        }

        public Criteria andMOVE_MATNotEqualTo(String value) {
            addCriterion("MOVE_MAT <>", value, "MOVE_MAT");
            return (Criteria) this;
        }

        public Criteria andMOVE_MATGreaterThan(String value) {
            addCriterion("MOVE_MAT >", value, "MOVE_MAT");
            return (Criteria) this;
        }

        public Criteria andMOVE_MATGreaterThanOrEqualTo(String value) {
            addCriterion("MOVE_MAT >=", value, "MOVE_MAT");
            return (Criteria) this;
        }

        public Criteria andMOVE_MATLessThan(String value) {
            addCriterion("MOVE_MAT <", value, "MOVE_MAT");
            return (Criteria) this;
        }

        public Criteria andMOVE_MATLessThanOrEqualTo(String value) {
            addCriterion("MOVE_MAT <=", value, "MOVE_MAT");
            return (Criteria) this;
        }

        public Criteria andMOVE_MATLike(String value) {
            addCriterion("MOVE_MAT like", value, "MOVE_MAT");
            return (Criteria) this;
        }

        public Criteria andMOVE_MATNotLike(String value) {
            addCriterion("MOVE_MAT not like", value, "MOVE_MAT");
            return (Criteria) this;
        }

        public Criteria andMOVE_MATIn(List<String> values) {
            addCriterion("MOVE_MAT in", values, "MOVE_MAT");
            return (Criteria) this;
        }

        public Criteria andMOVE_MATNotIn(List<String> values) {
            addCriterion("MOVE_MAT not in", values, "MOVE_MAT");
            return (Criteria) this;
        }

        public Criteria andMOVE_MATBetween(String value1, String value2) {
            addCriterion("MOVE_MAT between", value1, value2, "MOVE_MAT");
            return (Criteria) this;
        }

        public Criteria andMOVE_MATNotBetween(String value1, String value2) {
            addCriterion("MOVE_MAT not between", value1, value2, "MOVE_MAT");
            return (Criteria) this;
        }

        public Criteria andMOVE_BATCHIsNull() {
            addCriterion("MOVE_BATCH is null");
            return (Criteria) this;
        }

        public Criteria andMOVE_BATCHIsNotNull() {
            addCriterion("MOVE_BATCH is not null");
            return (Criteria) this;
        }

        public Criteria andMOVE_BATCHEqualTo(String value) {
            addCriterion("MOVE_BATCH =", value, "MOVE_BATCH");
            return (Criteria) this;
        }

        public Criteria andMOVE_BATCHNotEqualTo(String value) {
            addCriterion("MOVE_BATCH <>", value, "MOVE_BATCH");
            return (Criteria) this;
        }

        public Criteria andMOVE_BATCHGreaterThan(String value) {
            addCriterion("MOVE_BATCH >", value, "MOVE_BATCH");
            return (Criteria) this;
        }

        public Criteria andMOVE_BATCHGreaterThanOrEqualTo(String value) {
            addCriterion("MOVE_BATCH >=", value, "MOVE_BATCH");
            return (Criteria) this;
        }

        public Criteria andMOVE_BATCHLessThan(String value) {
            addCriterion("MOVE_BATCH <", value, "MOVE_BATCH");
            return (Criteria) this;
        }

        public Criteria andMOVE_BATCHLessThanOrEqualTo(String value) {
            addCriterion("MOVE_BATCH <=", value, "MOVE_BATCH");
            return (Criteria) this;
        }

        public Criteria andMOVE_BATCHLike(String value) {
            addCriterion("MOVE_BATCH like", value, "MOVE_BATCH");
            return (Criteria) this;
        }

        public Criteria andMOVE_BATCHNotLike(String value) {
            addCriterion("MOVE_BATCH not like", value, "MOVE_BATCH");
            return (Criteria) this;
        }

        public Criteria andMOVE_BATCHIn(List<String> values) {
            addCriterion("MOVE_BATCH in", values, "MOVE_BATCH");
            return (Criteria) this;
        }

        public Criteria andMOVE_BATCHNotIn(List<String> values) {
            addCriterion("MOVE_BATCH not in", values, "MOVE_BATCH");
            return (Criteria) this;
        }

        public Criteria andMOVE_BATCHBetween(String value1, String value2) {
            addCriterion("MOVE_BATCH between", value1, value2, "MOVE_BATCH");
            return (Criteria) this;
        }

        public Criteria andMOVE_BATCHNotBetween(String value1, String value2) {
            addCriterion("MOVE_BATCH not between", value1, value2, "MOVE_BATCH");
            return (Criteria) this;
        }

        public Criteria andMOVE_PLANTIsNull() {
            addCriterion("MOVE_PLANT is null");
            return (Criteria) this;
        }

        public Criteria andMOVE_PLANTIsNotNull() {
            addCriterion("MOVE_PLANT is not null");
            return (Criteria) this;
        }

        public Criteria andMOVE_PLANTEqualTo(String value) {
            addCriterion("MOVE_PLANT =", value, "MOVE_PLANT");
            return (Criteria) this;
        }

        public Criteria andMOVE_PLANTNotEqualTo(String value) {
            addCriterion("MOVE_PLANT <>", value, "MOVE_PLANT");
            return (Criteria) this;
        }

        public Criteria andMOVE_PLANTGreaterThan(String value) {
            addCriterion("MOVE_PLANT >", value, "MOVE_PLANT");
            return (Criteria) this;
        }

        public Criteria andMOVE_PLANTGreaterThanOrEqualTo(String value) {
            addCriterion("MOVE_PLANT >=", value, "MOVE_PLANT");
            return (Criteria) this;
        }

        public Criteria andMOVE_PLANTLessThan(String value) {
            addCriterion("MOVE_PLANT <", value, "MOVE_PLANT");
            return (Criteria) this;
        }

        public Criteria andMOVE_PLANTLessThanOrEqualTo(String value) {
            addCriterion("MOVE_PLANT <=", value, "MOVE_PLANT");
            return (Criteria) this;
        }

        public Criteria andMOVE_PLANTLike(String value) {
            addCriterion("MOVE_PLANT like", value, "MOVE_PLANT");
            return (Criteria) this;
        }

        public Criteria andMOVE_PLANTNotLike(String value) {
            addCriterion("MOVE_PLANT not like", value, "MOVE_PLANT");
            return (Criteria) this;
        }

        public Criteria andMOVE_PLANTIn(List<String> values) {
            addCriterion("MOVE_PLANT in", values, "MOVE_PLANT");
            return (Criteria) this;
        }

        public Criteria andMOVE_PLANTNotIn(List<String> values) {
            addCriterion("MOVE_PLANT not in", values, "MOVE_PLANT");
            return (Criteria) this;
        }

        public Criteria andMOVE_PLANTBetween(String value1, String value2) {
            addCriterion("MOVE_PLANT between", value1, value2, "MOVE_PLANT");
            return (Criteria) this;
        }

        public Criteria andMOVE_PLANTNotBetween(String value1, String value2) {
            addCriterion("MOVE_PLANT not between", value1, value2, "MOVE_PLANT");
            return (Criteria) this;
        }

        public Criteria andPO_ITEMIsNull() {
            addCriterion("PO_ITEM is null");
            return (Criteria) this;
        }

        public Criteria andPO_ITEMIsNotNull() {
            addCriterion("PO_ITEM is not null");
            return (Criteria) this;
        }

        public Criteria andPO_ITEMEqualTo(String value) {
            addCriterion("PO_ITEM =", value, "PO_ITEM");
            return (Criteria) this;
        }

        public Criteria andPO_ITEMNotEqualTo(String value) {
            addCriterion("PO_ITEM <>", value, "PO_ITEM");
            return (Criteria) this;
        }

        public Criteria andPO_ITEMGreaterThan(String value) {
            addCriterion("PO_ITEM >", value, "PO_ITEM");
            return (Criteria) this;
        }

        public Criteria andPO_ITEMGreaterThanOrEqualTo(String value) {
            addCriterion("PO_ITEM >=", value, "PO_ITEM");
            return (Criteria) this;
        }

        public Criteria andPO_ITEMLessThan(String value) {
            addCriterion("PO_ITEM <", value, "PO_ITEM");
            return (Criteria) this;
        }

        public Criteria andPO_ITEMLessThanOrEqualTo(String value) {
            addCriterion("PO_ITEM <=", value, "PO_ITEM");
            return (Criteria) this;
        }

        public Criteria andPO_ITEMLike(String value) {
            addCriterion("PO_ITEM like", value, "PO_ITEM");
            return (Criteria) this;
        }

        public Criteria andPO_ITEMNotLike(String value) {
            addCriterion("PO_ITEM not like", value, "PO_ITEM");
            return (Criteria) this;
        }

        public Criteria andPO_ITEMIn(List<String> values) {
            addCriterion("PO_ITEM in", values, "PO_ITEM");
            return (Criteria) this;
        }

        public Criteria andPO_ITEMNotIn(List<String> values) {
            addCriterion("PO_ITEM not in", values, "PO_ITEM");
            return (Criteria) this;
        }

        public Criteria andPO_ITEMBetween(String value1, String value2) {
            addCriterion("PO_ITEM between", value1, value2, "PO_ITEM");
            return (Criteria) this;
        }

        public Criteria andPO_ITEMNotBetween(String value1, String value2) {
            addCriterion("PO_ITEM not between", value1, value2, "PO_ITEM");
            return (Criteria) this;
        }

        public Criteria andPO_NUMBERIsNull() {
            addCriterion("PO_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andPO_NUMBERIsNotNull() {
            addCriterion("PO_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andPO_NUMBEREqualTo(String value) {
            addCriterion("PO_NUMBER =", value, "PO_NUMBER");
            return (Criteria) this;
        }

        public Criteria andPO_NUMBERNotEqualTo(String value) {
            addCriterion("PO_NUMBER <>", value, "PO_NUMBER");
            return (Criteria) this;
        }

        public Criteria andPO_NUMBERGreaterThan(String value) {
            addCriterion("PO_NUMBER >", value, "PO_NUMBER");
            return (Criteria) this;
        }

        public Criteria andPO_NUMBERGreaterThanOrEqualTo(String value) {
            addCriterion("PO_NUMBER >=", value, "PO_NUMBER");
            return (Criteria) this;
        }

        public Criteria andPO_NUMBERLessThan(String value) {
            addCriterion("PO_NUMBER <", value, "PO_NUMBER");
            return (Criteria) this;
        }

        public Criteria andPO_NUMBERLessThanOrEqualTo(String value) {
            addCriterion("PO_NUMBER <=", value, "PO_NUMBER");
            return (Criteria) this;
        }

        public Criteria andPO_NUMBERLike(String value) {
            addCriterion("PO_NUMBER like", value, "PO_NUMBER");
            return (Criteria) this;
        }

        public Criteria andPO_NUMBERNotLike(String value) {
            addCriterion("PO_NUMBER not like", value, "PO_NUMBER");
            return (Criteria) this;
        }

        public Criteria andPO_NUMBERIn(List<String> values) {
            addCriterion("PO_NUMBER in", values, "PO_NUMBER");
            return (Criteria) this;
        }

        public Criteria andPO_NUMBERNotIn(List<String> values) {
            addCriterion("PO_NUMBER not in", values, "PO_NUMBER");
            return (Criteria) this;
        }

        public Criteria andPO_NUMBERBetween(String value1, String value2) {
            addCriterion("PO_NUMBER between", value1, value2, "PO_NUMBER");
            return (Criteria) this;
        }

        public Criteria andPO_NUMBERNotBetween(String value1, String value2) {
            addCriterion("PO_NUMBER not between", value1, value2, "PO_NUMBER");
            return (Criteria) this;
        }

        public Criteria andORDERIDIsNull() {
            addCriterion("ORDERID is null");
            return (Criteria) this;
        }

        public Criteria andORDERIDIsNotNull() {
            addCriterion("ORDERID is not null");
            return (Criteria) this;
        }

        public Criteria andORDERIDEqualTo(String value) {
            addCriterion("ORDERID =", value, "ORDERID");
            return (Criteria) this;
        }

        public Criteria andORDERIDNotEqualTo(String value) {
            addCriterion("ORDERID <>", value, "ORDERID");
            return (Criteria) this;
        }

        public Criteria andORDERIDGreaterThan(String value) {
            addCriterion("ORDERID >", value, "ORDERID");
            return (Criteria) this;
        }

        public Criteria andORDERIDGreaterThanOrEqualTo(String value) {
            addCriterion("ORDERID >=", value, "ORDERID");
            return (Criteria) this;
        }

        public Criteria andORDERIDLessThan(String value) {
            addCriterion("ORDERID <", value, "ORDERID");
            return (Criteria) this;
        }

        public Criteria andORDERIDLessThanOrEqualTo(String value) {
            addCriterion("ORDERID <=", value, "ORDERID");
            return (Criteria) this;
        }

        public Criteria andORDERIDLike(String value) {
            addCriterion("ORDERID like", value, "ORDERID");
            return (Criteria) this;
        }

        public Criteria andORDERIDNotLike(String value) {
            addCriterion("ORDERID not like", value, "ORDERID");
            return (Criteria) this;
        }

        public Criteria andORDERIDIn(List<String> values) {
            addCriterion("ORDERID in", values, "ORDERID");
            return (Criteria) this;
        }

        public Criteria andORDERIDNotIn(List<String> values) {
            addCriterion("ORDERID not in", values, "ORDERID");
            return (Criteria) this;
        }

        public Criteria andORDERIDBetween(String value1, String value2) {
            addCriterion("ORDERID between", value1, value2, "ORDERID");
            return (Criteria) this;
        }

        public Criteria andORDERIDNotBetween(String value1, String value2) {
            addCriterion("ORDERID not between", value1, value2, "ORDERID");
            return (Criteria) this;
        }

        public Criteria andORDER_ITNOIsNull() {
            addCriterion("ORDER_ITNO is null");
            return (Criteria) this;
        }

        public Criteria andORDER_ITNOIsNotNull() {
            addCriterion("ORDER_ITNO is not null");
            return (Criteria) this;
        }

        public Criteria andORDER_ITNOEqualTo(String value) {
            addCriterion("ORDER_ITNO =", value, "ORDER_ITNO");
            return (Criteria) this;
        }

        public Criteria andORDER_ITNONotEqualTo(String value) {
            addCriterion("ORDER_ITNO <>", value, "ORDER_ITNO");
            return (Criteria) this;
        }

        public Criteria andORDER_ITNOGreaterThan(String value) {
            addCriterion("ORDER_ITNO >", value, "ORDER_ITNO");
            return (Criteria) this;
        }

        public Criteria andORDER_ITNOGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_ITNO >=", value, "ORDER_ITNO");
            return (Criteria) this;
        }

        public Criteria andORDER_ITNOLessThan(String value) {
            addCriterion("ORDER_ITNO <", value, "ORDER_ITNO");
            return (Criteria) this;
        }

        public Criteria andORDER_ITNOLessThanOrEqualTo(String value) {
            addCriterion("ORDER_ITNO <=", value, "ORDER_ITNO");
            return (Criteria) this;
        }

        public Criteria andORDER_ITNOLike(String value) {
            addCriterion("ORDER_ITNO like", value, "ORDER_ITNO");
            return (Criteria) this;
        }

        public Criteria andORDER_ITNONotLike(String value) {
            addCriterion("ORDER_ITNO not like", value, "ORDER_ITNO");
            return (Criteria) this;
        }

        public Criteria andORDER_ITNOIn(List<String> values) {
            addCriterion("ORDER_ITNO in", values, "ORDER_ITNO");
            return (Criteria) this;
        }

        public Criteria andORDER_ITNONotIn(List<String> values) {
            addCriterion("ORDER_ITNO not in", values, "ORDER_ITNO");
            return (Criteria) this;
        }

        public Criteria andORDER_ITNOBetween(String value1, String value2) {
            addCriterion("ORDER_ITNO between", value1, value2, "ORDER_ITNO");
            return (Criteria) this;
        }

        public Criteria andORDER_ITNONotBetween(String value1, String value2) {
            addCriterion("ORDER_ITNO not between", value1, value2, "ORDER_ITNO");
            return (Criteria) this;
        }

        public Criteria andREF_DOCIsNull() {
            addCriterion("REF_DOC is null");
            return (Criteria) this;
        }

        public Criteria andREF_DOCIsNotNull() {
            addCriterion("REF_DOC is not null");
            return (Criteria) this;
        }

        public Criteria andREF_DOCEqualTo(String value) {
            addCriterion("REF_DOC =", value, "REF_DOC");
            return (Criteria) this;
        }

        public Criteria andREF_DOCNotEqualTo(String value) {
            addCriterion("REF_DOC <>", value, "REF_DOC");
            return (Criteria) this;
        }

        public Criteria andREF_DOCGreaterThan(String value) {
            addCriterion("REF_DOC >", value, "REF_DOC");
            return (Criteria) this;
        }

        public Criteria andREF_DOCGreaterThanOrEqualTo(String value) {
            addCriterion("REF_DOC >=", value, "REF_DOC");
            return (Criteria) this;
        }

        public Criteria andREF_DOCLessThan(String value) {
            addCriterion("REF_DOC <", value, "REF_DOC");
            return (Criteria) this;
        }

        public Criteria andREF_DOCLessThanOrEqualTo(String value) {
            addCriterion("REF_DOC <=", value, "REF_DOC");
            return (Criteria) this;
        }

        public Criteria andREF_DOCLike(String value) {
            addCriterion("REF_DOC like", value, "REF_DOC");
            return (Criteria) this;
        }

        public Criteria andREF_DOCNotLike(String value) {
            addCriterion("REF_DOC not like", value, "REF_DOC");
            return (Criteria) this;
        }

        public Criteria andREF_DOCIn(List<String> values) {
            addCriterion("REF_DOC in", values, "REF_DOC");
            return (Criteria) this;
        }

        public Criteria andREF_DOCNotIn(List<String> values) {
            addCriterion("REF_DOC not in", values, "REF_DOC");
            return (Criteria) this;
        }

        public Criteria andREF_DOCBetween(String value1, String value2) {
            addCriterion("REF_DOC between", value1, value2, "REF_DOC");
            return (Criteria) this;
        }

        public Criteria andREF_DOCNotBetween(String value1, String value2) {
            addCriterion("REF_DOC not between", value1, value2, "REF_DOC");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YRIsNull() {
            addCriterion("REF_DOC_YR is null");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YRIsNotNull() {
            addCriterion("REF_DOC_YR is not null");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YREqualTo(String value) {
            addCriterion("REF_DOC_YR =", value, "REF_DOC_YR");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YRNotEqualTo(String value) {
            addCriterion("REF_DOC_YR <>", value, "REF_DOC_YR");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YRGreaterThan(String value) {
            addCriterion("REF_DOC_YR >", value, "REF_DOC_YR");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YRGreaterThanOrEqualTo(String value) {
            addCriterion("REF_DOC_YR >=", value, "REF_DOC_YR");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YRLessThan(String value) {
            addCriterion("REF_DOC_YR <", value, "REF_DOC_YR");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YRLessThanOrEqualTo(String value) {
            addCriterion("REF_DOC_YR <=", value, "REF_DOC_YR");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YRLike(String value) {
            addCriterion("REF_DOC_YR like", value, "REF_DOC_YR");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YRNotLike(String value) {
            addCriterion("REF_DOC_YR not like", value, "REF_DOC_YR");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YRIn(List<String> values) {
            addCriterion("REF_DOC_YR in", values, "REF_DOC_YR");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YRNotIn(List<String> values) {
            addCriterion("REF_DOC_YR not in", values, "REF_DOC_YR");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YRBetween(String value1, String value2) {
            addCriterion("REF_DOC_YR between", value1, value2, "REF_DOC_YR");
            return (Criteria) this;
        }

        public Criteria andREF_DOC_YRNotBetween(String value1, String value2) {
            addCriterion("REF_DOC_YR not between", value1, value2, "REF_DOC_YR");
            return (Criteria) this;
        }

        public Criteria andGRNIsNull() {
            addCriterion("GRN is null");
            return (Criteria) this;
        }

        public Criteria andGRNIsNotNull() {
            addCriterion("GRN is not null");
            return (Criteria) this;
        }

        public Criteria andGRNEqualTo(String value) {
            addCriterion("GRN =", value, "GRN");
            return (Criteria) this;
        }

        public Criteria andGRNNotEqualTo(String value) {
            addCriterion("GRN <>", value, "GRN");
            return (Criteria) this;
        }

        public Criteria andGRNGreaterThan(String value) {
            addCriterion("GRN >", value, "GRN");
            return (Criteria) this;
        }

        public Criteria andGRNGreaterThanOrEqualTo(String value) {
            addCriterion("GRN >=", value, "GRN");
            return (Criteria) this;
        }

        public Criteria andGRNLessThan(String value) {
            addCriterion("GRN <", value, "GRN");
            return (Criteria) this;
        }

        public Criteria andGRNLessThanOrEqualTo(String value) {
            addCriterion("GRN <=", value, "GRN");
            return (Criteria) this;
        }

        public Criteria andGRNLike(String value) {
            addCriterion("GRN like", value, "GRN");
            return (Criteria) this;
        }

        public Criteria andGRNNotLike(String value) {
            addCriterion("GRN not like", value, "GRN");
            return (Criteria) this;
        }

        public Criteria andGRNIn(List<String> values) {
            addCriterion("GRN in", values, "GRN");
            return (Criteria) this;
        }

        public Criteria andGRNNotIn(List<String> values) {
            addCriterion("GRN not in", values, "GRN");
            return (Criteria) this;
        }

        public Criteria andGRNBetween(String value1, String value2) {
            addCriterion("GRN between", value1, value2, "GRN");
            return (Criteria) this;
        }

        public Criteria andGRNNotBetween(String value1, String value2) {
            addCriterion("GRN not between", value1, value2, "GRN");
            return (Criteria) this;
        }

        public Criteria andTO_NameIsNull() {
            addCriterion("TO_Name is null");
            return (Criteria) this;
        }

        public Criteria andTO_NameIsNotNull() {
            addCriterion("TO_Name is not null");
            return (Criteria) this;
        }

        public Criteria andTO_NameEqualTo(String value) {
            addCriterion("TO_Name =", value, "TO_Name");
            return (Criteria) this;
        }

        public Criteria andTO_NameNotEqualTo(String value) {
            addCriterion("TO_Name <>", value, "TO_Name");
            return (Criteria) this;
        }

        public Criteria andTO_NameGreaterThan(String value) {
            addCriterion("TO_Name >", value, "TO_Name");
            return (Criteria) this;
        }

        public Criteria andTO_NameGreaterThanOrEqualTo(String value) {
            addCriterion("TO_Name >=", value, "TO_Name");
            return (Criteria) this;
        }

        public Criteria andTO_NameLessThan(String value) {
            addCriterion("TO_Name <", value, "TO_Name");
            return (Criteria) this;
        }

        public Criteria andTO_NameLessThanOrEqualTo(String value) {
            addCriterion("TO_Name <=", value, "TO_Name");
            return (Criteria) this;
        }

        public Criteria andTO_NameLike(String value) {
            addCriterion("TO_Name like", value, "TO_Name");
            return (Criteria) this;
        }

        public Criteria andTO_NameNotLike(String value) {
            addCriterion("TO_Name not like", value, "TO_Name");
            return (Criteria) this;
        }

        public Criteria andTO_NameIn(List<String> values) {
            addCriterion("TO_Name in", values, "TO_Name");
            return (Criteria) this;
        }

        public Criteria andTO_NameNotIn(List<String> values) {
            addCriterion("TO_Name not in", values, "TO_Name");
            return (Criteria) this;
        }

        public Criteria andTO_NameBetween(String value1, String value2) {
            addCriterion("TO_Name between", value1, value2, "TO_Name");
            return (Criteria) this;
        }

        public Criteria andTO_NameNotBetween(String value1, String value2) {
            addCriterion("TO_Name not between", value1, value2, "TO_Name");
            return (Criteria) this;
        }

        public Criteria andHasRunIsNull() {
            addCriterion("HasRun is null");
            return (Criteria) this;
        }

        public Criteria andHasRunIsNotNull() {
            addCriterion("HasRun is not null");
            return (Criteria) this;
        }

        public Criteria andHasRunEqualTo(Integer value) {
            addCriterion("HasRun =", value, "hasRun");
            return (Criteria) this;
        }

        public Criteria andHasRunNotEqualTo(Integer value) {
            addCriterion("HasRun <>", value, "hasRun");
            return (Criteria) this;
        }

        public Criteria andHasRunGreaterThan(Integer value) {
            addCriterion("HasRun >", value, "hasRun");
            return (Criteria) this;
        }

        public Criteria andHasRunGreaterThanOrEqualTo(Integer value) {
            addCriterion("HasRun >=", value, "hasRun");
            return (Criteria) this;
        }

        public Criteria andHasRunLessThan(Integer value) {
            addCriterion("HasRun <", value, "hasRun");
            return (Criteria) this;
        }

        public Criteria andHasRunLessThanOrEqualTo(Integer value) {
            addCriterion("HasRun <=", value, "hasRun");
            return (Criteria) this;
        }

        public Criteria andHasRunIn(List<Integer> values) {
            addCriterion("HasRun in", values, "hasRun");
            return (Criteria) this;
        }

        public Criteria andHasRunNotIn(List<Integer> values) {
            addCriterion("HasRun not in", values, "hasRun");
            return (Criteria) this;
        }

        public Criteria andHasRunBetween(Integer value1, Integer value2) {
            addCriterion("HasRun between", value1, value2, "hasRun");
            return (Criteria) this;
        }

        public Criteria andHasRunNotBetween(Integer value1, Integer value2) {
            addCriterion("HasRun not between", value1, value2, "hasRun");
            return (Criteria) this;
        }

        public Criteria andInsert_311_optionIsNull() {
            addCriterion("insert_311_option is null");
            return (Criteria) this;
        }

        public Criteria andInsert_311_optionIsNotNull() {
            addCriterion("insert_311_option is not null");
            return (Criteria) this;
        }

        public Criteria andInsert_311_optionEqualTo(String value) {
            addCriterion("insert_311_option =", value, "insert_311_option");
            return (Criteria) this;
        }

        public Criteria andInsert_311_optionNotEqualTo(String value) {
            addCriterion("insert_311_option <>", value, "insert_311_option");
            return (Criteria) this;
        }

        public Criteria andInsert_311_optionGreaterThan(String value) {
            addCriterion("insert_311_option >", value, "insert_311_option");
            return (Criteria) this;
        }

        public Criteria andInsert_311_optionGreaterThanOrEqualTo(String value) {
            addCriterion("insert_311_option >=", value, "insert_311_option");
            return (Criteria) this;
        }

        public Criteria andInsert_311_optionLessThan(String value) {
            addCriterion("insert_311_option <", value, "insert_311_option");
            return (Criteria) this;
        }

        public Criteria andInsert_311_optionLessThanOrEqualTo(String value) {
            addCriterion("insert_311_option <=", value, "insert_311_option");
            return (Criteria) this;
        }

        public Criteria andInsert_311_optionLike(String value) {
            addCriterion("insert_311_option like", value, "insert_311_option");
            return (Criteria) this;
        }

        public Criteria andInsert_311_optionNotLike(String value) {
            addCriterion("insert_311_option not like", value, "insert_311_option");
            return (Criteria) this;
        }

        public Criteria andInsert_311_optionIn(List<String> values) {
            addCriterion("insert_311_option in", values, "insert_311_option");
            return (Criteria) this;
        }

        public Criteria andInsert_311_optionNotIn(List<String> values) {
            addCriterion("insert_311_option not in", values, "insert_311_option");
            return (Criteria) this;
        }

        public Criteria andInsert_311_optionBetween(String value1, String value2) {
            addCriterion("insert_311_option between", value1, value2, "insert_311_option");
            return (Criteria) this;
        }

        public Criteria andInsert_311_optionNotBetween(String value1, String value2) {
            addCriterion("insert_311_option not between", value1, value2, "insert_311_option");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xTend_MaterialTransactionsSummary
     *
     * @mbggenerated do_not_delete_during_merge Mon Dec 19 14:31:30 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table xTend_MaterialTransactionsSummary
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}