package com.ht.entity;

import java.util.Date;

public class TransactionLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTxnLog.Module
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String module;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTxnLog.TxnType
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String txnType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTxnLog.BatchId
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String batchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTxnLog.ItemId
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTxnLog.Time
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTxnLog.Result
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String result;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTxnLog.Message
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTxnLog.SAPREF_DOC
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String SAPREF_DOC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTxnLog.SAPREF_YEAR
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String SAPREF_YEAR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTxnLog.POSTBatchID
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String POSTBatchID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTxnLog.Module
     *
     * @return the value of xTend_MaterialTxnLog.Module
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getModule() {
        return module;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTxnLog.Module
     *
     * @param module the value for xTend_MaterialTxnLog.Module
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setModule(String module) {
        this.module = module == null ? null : module.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTxnLog.TxnType
     *
     * @return the value of xTend_MaterialTxnLog.TxnType
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getTxnType() {
        return txnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTxnLog.TxnType
     *
     * @param txnType the value for xTend_MaterialTxnLog.TxnType
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setTxnType(String txnType) {
        this.txnType = txnType == null ? null : txnType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTxnLog.BatchId
     *
     * @return the value of xTend_MaterialTxnLog.BatchId
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTxnLog.BatchId
     *
     * @param batchId the value for xTend_MaterialTxnLog.BatchId
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setBatchId(String batchId) {
        this.batchId = batchId == null ? null : batchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTxnLog.ItemId
     *
     * @return the value of xTend_MaterialTxnLog.ItemId
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTxnLog.ItemId
     *
     * @param itemId the value for xTend_MaterialTxnLog.ItemId
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTxnLog.Time
     *
     * @return the value of xTend_MaterialTxnLog.Time
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTxnLog.Time
     *
     * @param time the value for xTend_MaterialTxnLog.Time
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTxnLog.Result
     *
     * @return the value of xTend_MaterialTxnLog.Result
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTxnLog.Result
     *
     * @param result the value for xTend_MaterialTxnLog.Result
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setResult(String result) {
        this.result = result == null ? null : result.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTxnLog.Message
     *
     * @return the value of xTend_MaterialTxnLog.Message
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTxnLog.Message
     *
     * @param message the value for xTend_MaterialTxnLog.Message
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTxnLog.SAPREF_DOC
     *
     * @return the value of xTend_MaterialTxnLog.SAPREF_DOC
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getSAPREF_DOC() {
        return SAPREF_DOC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTxnLog.SAPREF_DOC
     *
     * @param SAPREF_DOC the value for xTend_MaterialTxnLog.SAPREF_DOC
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setSAPREF_DOC(String SAPREF_DOC) {
        this.SAPREF_DOC = SAPREF_DOC == null ? null : SAPREF_DOC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTxnLog.SAPREF_YEAR
     *
     * @return the value of xTend_MaterialTxnLog.SAPREF_YEAR
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getSAPREF_YEAR() {
        return SAPREF_YEAR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTxnLog.SAPREF_YEAR
     *
     * @param SAPREF_YEAR the value for xTend_MaterialTxnLog.SAPREF_YEAR
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setSAPREF_YEAR(String SAPREF_YEAR) {
        this.SAPREF_YEAR = SAPREF_YEAR == null ? null : SAPREF_YEAR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTxnLog.POSTBatchID
     *
     * @return the value of xTend_MaterialTxnLog.POSTBatchID
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getPOSTBatchID() {
        return POSTBatchID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTxnLog.POSTBatchID
     *
     * @param POSTBatchID the value for xTend_MaterialTxnLog.POSTBatchID
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setPOSTBatchID(String POSTBatchID) {
        this.POSTBatchID = POSTBatchID == null ? null : POSTBatchID.trim();
    }
}