package com.ht.entity;

import java.util.Date;

public class TransactionSummary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.BatchId
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String batchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.ItemId
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.Batch
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String batch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.PartNumber
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String partNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.FromStock
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String fromStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.ToStock
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String toStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.Quantity
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private Double quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.UOM
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String UOM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.TransactionUser
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String transactionUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.TransactionTime
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private Date transactionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.TransactionType
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String transactionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.TransactionReason
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String transactionReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.TransactionResult
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private Integer transactionResult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.RetryCount
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private Integer retryCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.RFCTemplateID
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String RFCTemplateID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.RefDocNo
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String refDocNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.DocHeader
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String docHeader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.Plant
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String plant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.Vendor
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String vendor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.SpecialStock
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String specialStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.I_PRUEFLOS
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String i_PRUEFLOS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.I_VCODE
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String i_VCODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.GR_RCPT
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String GR_RCPT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.COSTCENTER
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String COSTCENTER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.IND_PROPOSE_QUANX
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String IND_PROPOSE_QUANX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.MOVE_MAT
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String MOVE_MAT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.MOVE_BATCH
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String MOVE_BATCH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.MOVE_PLANT
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String MOVE_PLANT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.PO_ITEM
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String PO_ITEM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.PO_NUMBER
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String PO_NUMBER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.ORDERID
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String ORDERID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.ORDER_ITNO
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String ORDER_ITNO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.REF_DOC
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String REF_DOC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.REF_DOC_YR
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String REF_DOC_YR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.GRN
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String GRN;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.TO_Name
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String TO_Name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.HasRun
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private Integer hasRun;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactionsSummary.insert_311_option
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    private String insert_311_option;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.BatchId
     *
     * @return the value of xTend_MaterialTransactionsSummary.BatchId
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.BatchId
     *
     * @param batchId the value for xTend_MaterialTransactionsSummary.BatchId
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setBatchId(String batchId) {
        this.batchId = batchId == null ? null : batchId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.ItemId
     *
     * @return the value of xTend_MaterialTransactionsSummary.ItemId
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.ItemId
     *
     * @param itemId the value for xTend_MaterialTransactionsSummary.ItemId
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.Batch
     *
     * @return the value of xTend_MaterialTransactionsSummary.Batch
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getBatch() {
        return batch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.Batch
     *
     * @param batch the value for xTend_MaterialTransactionsSummary.Batch
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setBatch(String batch) {
        this.batch = batch == null ? null : batch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.PartNumber
     *
     * @return the value of xTend_MaterialTransactionsSummary.PartNumber
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getPartNumber() {
        return partNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.PartNumber
     *
     * @param partNumber the value for xTend_MaterialTransactionsSummary.PartNumber
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setPartNumber(String partNumber) {
        this.partNumber = partNumber == null ? null : partNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.FromStock
     *
     * @return the value of xTend_MaterialTransactionsSummary.FromStock
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getFromStock() {
        return fromStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.FromStock
     *
     * @param fromStock the value for xTend_MaterialTransactionsSummary.FromStock
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setFromStock(String fromStock) {
        this.fromStock = fromStock == null ? null : fromStock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.ToStock
     *
     * @return the value of xTend_MaterialTransactionsSummary.ToStock
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getToStock() {
        return toStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.ToStock
     *
     * @param toStock the value for xTend_MaterialTransactionsSummary.ToStock
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setToStock(String toStock) {
        this.toStock = toStock == null ? null : toStock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.Quantity
     *
     * @return the value of xTend_MaterialTransactionsSummary.Quantity
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public Double getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.Quantity
     *
     * @param quantity the value for xTend_MaterialTransactionsSummary.Quantity
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.UOM
     *
     * @return the value of xTend_MaterialTransactionsSummary.UOM
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getUOM() {
        return UOM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.UOM
     *
     * @param UOM the value for xTend_MaterialTransactionsSummary.UOM
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setUOM(String UOM) {
        this.UOM = UOM == null ? null : UOM.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.TransactionUser
     *
     * @return the value of xTend_MaterialTransactionsSummary.TransactionUser
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getTransactionUser() {
        return transactionUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.TransactionUser
     *
     * @param transactionUser the value for xTend_MaterialTransactionsSummary.TransactionUser
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setTransactionUser(String transactionUser) {
        this.transactionUser = transactionUser == null ? null : transactionUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.TransactionTime
     *
     * @return the value of xTend_MaterialTransactionsSummary.TransactionTime
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public Date getTransactionTime() {
        return transactionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.TransactionTime
     *
     * @param transactionTime the value for xTend_MaterialTransactionsSummary.TransactionTime
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setTransactionTime(Date transactionTime) {
        this.transactionTime = transactionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.TransactionType
     *
     * @return the value of xTend_MaterialTransactionsSummary.TransactionType
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.TransactionType
     *
     * @param transactionType the value for xTend_MaterialTransactionsSummary.TransactionType
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType == null ? null : transactionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.TransactionReason
     *
     * @return the value of xTend_MaterialTransactionsSummary.TransactionReason
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getTransactionReason() {
        return transactionReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.TransactionReason
     *
     * @param transactionReason the value for xTend_MaterialTransactionsSummary.TransactionReason
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setTransactionReason(String transactionReason) {
        this.transactionReason = transactionReason == null ? null : transactionReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.TransactionResult
     *
     * @return the value of xTend_MaterialTransactionsSummary.TransactionResult
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public Integer getTransactionResult() {
        return transactionResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.TransactionResult
     *
     * @param transactionResult the value for xTend_MaterialTransactionsSummary.TransactionResult
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setTransactionResult(Integer transactionResult) {
        this.transactionResult = transactionResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.RetryCount
     *
     * @return the value of xTend_MaterialTransactionsSummary.RetryCount
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public Integer getRetryCount() {
        return retryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.RetryCount
     *
     * @param retryCount the value for xTend_MaterialTransactionsSummary.RetryCount
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setRetryCount(Integer retryCount) {
        this.retryCount = retryCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.RFCTemplateID
     *
     * @return the value of xTend_MaterialTransactionsSummary.RFCTemplateID
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getRFCTemplateID() {
        return RFCTemplateID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.RFCTemplateID
     *
     * @param RFCTemplateID the value for xTend_MaterialTransactionsSummary.RFCTemplateID
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setRFCTemplateID(String RFCTemplateID) {
        this.RFCTemplateID = RFCTemplateID == null ? null : RFCTemplateID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.RefDocNo
     *
     * @return the value of xTend_MaterialTransactionsSummary.RefDocNo
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getRefDocNo() {
        return refDocNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.RefDocNo
     *
     * @param refDocNo the value for xTend_MaterialTransactionsSummary.RefDocNo
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setRefDocNo(String refDocNo) {
        this.refDocNo = refDocNo == null ? null : refDocNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.DocHeader
     *
     * @return the value of xTend_MaterialTransactionsSummary.DocHeader
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getDocHeader() {
        return docHeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.DocHeader
     *
     * @param docHeader the value for xTend_MaterialTransactionsSummary.DocHeader
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setDocHeader(String docHeader) {
        this.docHeader = docHeader == null ? null : docHeader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.Plant
     *
     * @return the value of xTend_MaterialTransactionsSummary.Plant
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getPlant() {
        return plant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.Plant
     *
     * @param plant the value for xTend_MaterialTransactionsSummary.Plant
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setPlant(String plant) {
        this.plant = plant == null ? null : plant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.Vendor
     *
     * @return the value of xTend_MaterialTransactionsSummary.Vendor
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.Vendor
     *
     * @param vendor the value for xTend_MaterialTransactionsSummary.Vendor
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setVendor(String vendor) {
        this.vendor = vendor == null ? null : vendor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.SpecialStock
     *
     * @return the value of xTend_MaterialTransactionsSummary.SpecialStock
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getSpecialStock() {
        return specialStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.SpecialStock
     *
     * @param specialStock the value for xTend_MaterialTransactionsSummary.SpecialStock
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setSpecialStock(String specialStock) {
        this.specialStock = specialStock == null ? null : specialStock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.I_PRUEFLOS
     *
     * @return the value of xTend_MaterialTransactionsSummary.I_PRUEFLOS
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getI_PRUEFLOS() {
        return i_PRUEFLOS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.I_PRUEFLOS
     *
     * @param i_PRUEFLOS the value for xTend_MaterialTransactionsSummary.I_PRUEFLOS
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setI_PRUEFLOS(String i_PRUEFLOS) {
        this.i_PRUEFLOS = i_PRUEFLOS == null ? null : i_PRUEFLOS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.I_VCODE
     *
     * @return the value of xTend_MaterialTransactionsSummary.I_VCODE
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getI_VCODE() {
        return i_VCODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.I_VCODE
     *
     * @param i_VCODE the value for xTend_MaterialTransactionsSummary.I_VCODE
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setI_VCODE(String i_VCODE) {
        this.i_VCODE = i_VCODE == null ? null : i_VCODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.GR_RCPT
     *
     * @return the value of xTend_MaterialTransactionsSummary.GR_RCPT
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getGR_RCPT() {
        return GR_RCPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.GR_RCPT
     *
     * @param GR_RCPT the value for xTend_MaterialTransactionsSummary.GR_RCPT
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setGR_RCPT(String GR_RCPT) {
        this.GR_RCPT = GR_RCPT == null ? null : GR_RCPT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.COSTCENTER
     *
     * @return the value of xTend_MaterialTransactionsSummary.COSTCENTER
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getCOSTCENTER() {
        return COSTCENTER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.COSTCENTER
     *
     * @param COSTCENTER the value for xTend_MaterialTransactionsSummary.COSTCENTER
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setCOSTCENTER(String COSTCENTER) {
        this.COSTCENTER = COSTCENTER == null ? null : COSTCENTER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.IND_PROPOSE_QUANX
     *
     * @return the value of xTend_MaterialTransactionsSummary.IND_PROPOSE_QUANX
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getIND_PROPOSE_QUANX() {
        return IND_PROPOSE_QUANX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.IND_PROPOSE_QUANX
     *
     * @param IND_PROPOSE_QUANX the value for xTend_MaterialTransactionsSummary.IND_PROPOSE_QUANX
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setIND_PROPOSE_QUANX(String IND_PROPOSE_QUANX) {
        this.IND_PROPOSE_QUANX = IND_PROPOSE_QUANX == null ? null : IND_PROPOSE_QUANX.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.MOVE_MAT
     *
     * @return the value of xTend_MaterialTransactionsSummary.MOVE_MAT
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getMOVE_MAT() {
        return MOVE_MAT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.MOVE_MAT
     *
     * @param MOVE_MAT the value for xTend_MaterialTransactionsSummary.MOVE_MAT
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setMOVE_MAT(String MOVE_MAT) {
        this.MOVE_MAT = MOVE_MAT == null ? null : MOVE_MAT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.MOVE_BATCH
     *
     * @return the value of xTend_MaterialTransactionsSummary.MOVE_BATCH
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getMOVE_BATCH() {
        return MOVE_BATCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.MOVE_BATCH
     *
     * @param MOVE_BATCH the value for xTend_MaterialTransactionsSummary.MOVE_BATCH
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setMOVE_BATCH(String MOVE_BATCH) {
        this.MOVE_BATCH = MOVE_BATCH == null ? null : MOVE_BATCH.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.MOVE_PLANT
     *
     * @return the value of xTend_MaterialTransactionsSummary.MOVE_PLANT
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getMOVE_PLANT() {
        return MOVE_PLANT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.MOVE_PLANT
     *
     * @param MOVE_PLANT the value for xTend_MaterialTransactionsSummary.MOVE_PLANT
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setMOVE_PLANT(String MOVE_PLANT) {
        this.MOVE_PLANT = MOVE_PLANT == null ? null : MOVE_PLANT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.PO_ITEM
     *
     * @return the value of xTend_MaterialTransactionsSummary.PO_ITEM
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getPO_ITEM() {
        return PO_ITEM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.PO_ITEM
     *
     * @param PO_ITEM the value for xTend_MaterialTransactionsSummary.PO_ITEM
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setPO_ITEM(String PO_ITEM) {
        this.PO_ITEM = PO_ITEM == null ? null : PO_ITEM.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.PO_NUMBER
     *
     * @return the value of xTend_MaterialTransactionsSummary.PO_NUMBER
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getPO_NUMBER() {
        return PO_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.PO_NUMBER
     *
     * @param PO_NUMBER the value for xTend_MaterialTransactionsSummary.PO_NUMBER
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setPO_NUMBER(String PO_NUMBER) {
        this.PO_NUMBER = PO_NUMBER == null ? null : PO_NUMBER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.ORDERID
     *
     * @return the value of xTend_MaterialTransactionsSummary.ORDERID
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getORDERID() {
        return ORDERID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.ORDERID
     *
     * @param ORDERID the value for xTend_MaterialTransactionsSummary.ORDERID
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setORDERID(String ORDERID) {
        this.ORDERID = ORDERID == null ? null : ORDERID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.ORDER_ITNO
     *
     * @return the value of xTend_MaterialTransactionsSummary.ORDER_ITNO
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getORDER_ITNO() {
        return ORDER_ITNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.ORDER_ITNO
     *
     * @param ORDER_ITNO the value for xTend_MaterialTransactionsSummary.ORDER_ITNO
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setORDER_ITNO(String ORDER_ITNO) {
        this.ORDER_ITNO = ORDER_ITNO == null ? null : ORDER_ITNO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.REF_DOC
     *
     * @return the value of xTend_MaterialTransactionsSummary.REF_DOC
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getREF_DOC() {
        return REF_DOC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.REF_DOC
     *
     * @param REF_DOC the value for xTend_MaterialTransactionsSummary.REF_DOC
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setREF_DOC(String REF_DOC) {
        this.REF_DOC = REF_DOC == null ? null : REF_DOC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.REF_DOC_YR
     *
     * @return the value of xTend_MaterialTransactionsSummary.REF_DOC_YR
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getREF_DOC_YR() {
        return REF_DOC_YR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.REF_DOC_YR
     *
     * @param REF_DOC_YR the value for xTend_MaterialTransactionsSummary.REF_DOC_YR
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setREF_DOC_YR(String REF_DOC_YR) {
        this.REF_DOC_YR = REF_DOC_YR == null ? null : REF_DOC_YR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.GRN
     *
     * @return the value of xTend_MaterialTransactionsSummary.GRN
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getGRN() {
        return GRN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.GRN
     *
     * @param GRN the value for xTend_MaterialTransactionsSummary.GRN
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setGRN(String GRN) {
        this.GRN = GRN == null ? null : GRN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.TO_Name
     *
     * @return the value of xTend_MaterialTransactionsSummary.TO_Name
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getTO_Name() {
        return TO_Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.TO_Name
     *
     * @param TO_Name the value for xTend_MaterialTransactionsSummary.TO_Name
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setTO_Name(String TO_Name) {
        this.TO_Name = TO_Name == null ? null : TO_Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.HasRun
     *
     * @return the value of xTend_MaterialTransactionsSummary.HasRun
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public Integer getHasRun() {
        return hasRun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.HasRun
     *
     * @param hasRun the value for xTend_MaterialTransactionsSummary.HasRun
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setHasRun(Integer hasRun) {
        this.hasRun = hasRun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactionsSummary.insert_311_option
     *
     * @return the value of xTend_MaterialTransactionsSummary.insert_311_option
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public String getInsert_311_option() {
        return insert_311_option;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactionsSummary.insert_311_option
     *
     * @param insert_311_option the value for xTend_MaterialTransactionsSummary.insert_311_option
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    public void setInsert_311_option(String insert_311_option) {
        this.insert_311_option = insert_311_option == null ? null : insert_311_option.trim();
    }
}