package com.ht.entity;

import java.util.Date;

public class Transaction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.TransactionHistoryId
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String transactionHistoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.Batch
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String batch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.PartNumber
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String partNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.UID
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String UID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.Quantity
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private Double quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.UOM
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String UOM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.FromStock
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String fromStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.ToStock
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String toStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.TransactionUser
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String transactionUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.TransactionTime
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private Date transactionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.RecordStatus
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private Integer recordStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.TransactionType
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String transactionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.TransactionReason
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String transactionReason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.RFCTemplateID
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String RFCTemplateID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.RefDocNo
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String refDocNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.DocHeader
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String docHeader;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.DocHeader1
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String docHeader1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.Plant
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String plant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.Vendor
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String vendor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.SpecialStock
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String specialStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.FromStockLocation
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String fromStockLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.ToStockLocation
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String toStockLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.ERPFromStock
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String ERPFromStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.ERPToStock
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String ERPToStock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.I_PRUEFLOS
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String i_PRUEFLOS;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.I_VCODE
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String i_VCODE;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.GR_RCPT
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String GR_RCPT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.COSTCENTER
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String COSTCENTER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.IND_PROPOSE_QUANX
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String IND_PROPOSE_QUANX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.MOVE_MAT
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String MOVE_MAT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.MOVE_BATCH
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String MOVE_BATCH;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.MOVE_PLANT
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String MOVE_PLANT;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.PO_ITEM
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String PO_ITEM;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.PO_NUMBER
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String PO_NUMBER;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.ORDERID
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String ORDERID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.ORDER_ITNO
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String ORDER_ITNO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.REF_DOC
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String REF_DOC;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.REF_DOC_YR
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String REF_DOC_YR;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.GRN
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String GRN;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.TO_Name
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String TO_Name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.Remarks_351
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String remarks_351;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.insert_311_option
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String insert_311_option;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.PO_TO_PO
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String PO_TO_PO;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.Qty_261
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private Double qty_261;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.SmartCar_Status
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String smartCar_Status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xTend_MaterialTransactions.Car_No
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    private String car_No;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.TransactionHistoryId
     *
     * @return the value of xTend_MaterialTransactions.TransactionHistoryId
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getTransactionHistoryId() {
        return transactionHistoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.TransactionHistoryId
     *
     * @param transactionHistoryId the value for xTend_MaterialTransactions.TransactionHistoryId
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setTransactionHistoryId(String transactionHistoryId) {
        this.transactionHistoryId = transactionHistoryId == null ? null : transactionHistoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.Batch
     *
     * @return the value of xTend_MaterialTransactions.Batch
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getBatch() {
        return batch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.Batch
     *
     * @param batch the value for xTend_MaterialTransactions.Batch
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setBatch(String batch) {
        this.batch = batch == null ? null : batch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.PartNumber
     *
     * @return the value of xTend_MaterialTransactions.PartNumber
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getPartNumber() {
        return partNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.PartNumber
     *
     * @param partNumber the value for xTend_MaterialTransactions.PartNumber
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setPartNumber(String partNumber) {
        this.partNumber = partNumber == null ? null : partNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.UID
     *
     * @return the value of xTend_MaterialTransactions.UID
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getUID() {
        return UID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.UID
     *
     * @param UID the value for xTend_MaterialTransactions.UID
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setUID(String UID) {
        this.UID = UID == null ? null : UID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.Quantity
     *
     * @return the value of xTend_MaterialTransactions.Quantity
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public Double getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.Quantity
     *
     * @param quantity the value for xTend_MaterialTransactions.Quantity
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setQuantity(Double quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.UOM
     *
     * @return the value of xTend_MaterialTransactions.UOM
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getUOM() {
        return UOM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.UOM
     *
     * @param UOM the value for xTend_MaterialTransactions.UOM
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setUOM(String UOM) {
        this.UOM = UOM == null ? null : UOM.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.FromStock
     *
     * @return the value of xTend_MaterialTransactions.FromStock
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getFromStock() {
        return fromStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.FromStock
     *
     * @param fromStock the value for xTend_MaterialTransactions.FromStock
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setFromStock(String fromStock) {
        this.fromStock = fromStock == null ? null : fromStock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.ToStock
     *
     * @return the value of xTend_MaterialTransactions.ToStock
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getToStock() {
        return toStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.ToStock
     *
     * @param toStock the value for xTend_MaterialTransactions.ToStock
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setToStock(String toStock) {
        this.toStock = toStock == null ? null : toStock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.TransactionUser
     *
     * @return the value of xTend_MaterialTransactions.TransactionUser
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getTransactionUser() {
        return transactionUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.TransactionUser
     *
     * @param transactionUser the value for xTend_MaterialTransactions.TransactionUser
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setTransactionUser(String transactionUser) {
        this.transactionUser = transactionUser == null ? null : transactionUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.TransactionTime
     *
     * @return the value of xTend_MaterialTransactions.TransactionTime
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public Date getTransactionTime() {
        return transactionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.TransactionTime
     *
     * @param transactionTime the value for xTend_MaterialTransactions.TransactionTime
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setTransactionTime(Date transactionTime) {
        this.transactionTime = transactionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.RecordStatus
     *
     * @return the value of xTend_MaterialTransactions.RecordStatus
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public Integer getRecordStatus() {
        return recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.RecordStatus
     *
     * @param recordStatus the value for xTend_MaterialTransactions.RecordStatus
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setRecordStatus(Integer recordStatus) {
        this.recordStatus = recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.TransactionType
     *
     * @return the value of xTend_MaterialTransactions.TransactionType
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getTransactionType() {
        return transactionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.TransactionType
     *
     * @param transactionType the value for xTend_MaterialTransactions.TransactionType
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setTransactionType(String transactionType) {
        this.transactionType = transactionType == null ? null : transactionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.TransactionReason
     *
     * @return the value of xTend_MaterialTransactions.TransactionReason
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getTransactionReason() {
        return transactionReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.TransactionReason
     *
     * @param transactionReason the value for xTend_MaterialTransactions.TransactionReason
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setTransactionReason(String transactionReason) {
        this.transactionReason = transactionReason == null ? null : transactionReason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.RFCTemplateID
     *
     * @return the value of xTend_MaterialTransactions.RFCTemplateID
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getRFCTemplateID() {
        return RFCTemplateID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.RFCTemplateID
     *
     * @param RFCTemplateID the value for xTend_MaterialTransactions.RFCTemplateID
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setRFCTemplateID(String RFCTemplateID) {
        this.RFCTemplateID = RFCTemplateID == null ? null : RFCTemplateID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.RefDocNo
     *
     * @return the value of xTend_MaterialTransactions.RefDocNo
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getRefDocNo() {
        return refDocNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.RefDocNo
     *
     * @param refDocNo the value for xTend_MaterialTransactions.RefDocNo
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setRefDocNo(String refDocNo) {
        this.refDocNo = refDocNo == null ? null : refDocNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.DocHeader
     *
     * @return the value of xTend_MaterialTransactions.DocHeader
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getDocHeader() {
        return docHeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.DocHeader
     *
     * @param docHeader the value for xTend_MaterialTransactions.DocHeader
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setDocHeader(String docHeader) {
        this.docHeader = docHeader == null ? null : docHeader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.DocHeader1
     *
     * @return the value of xTend_MaterialTransactions.DocHeader1
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getDocHeader1() {
        return docHeader1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.DocHeader1
     *
     * @param docHeader1 the value for xTend_MaterialTransactions.DocHeader1
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setDocHeader1(String docHeader1) {
        this.docHeader1 = docHeader1 == null ? null : docHeader1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.Plant
     *
     * @return the value of xTend_MaterialTransactions.Plant
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getPlant() {
        return plant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.Plant
     *
     * @param plant the value for xTend_MaterialTransactions.Plant
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setPlant(String plant) {
        this.plant = plant == null ? null : plant.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.Vendor
     *
     * @return the value of xTend_MaterialTransactions.Vendor
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getVendor() {
        return vendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.Vendor
     *
     * @param vendor the value for xTend_MaterialTransactions.Vendor
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setVendor(String vendor) {
        this.vendor = vendor == null ? null : vendor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.SpecialStock
     *
     * @return the value of xTend_MaterialTransactions.SpecialStock
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getSpecialStock() {
        return specialStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.SpecialStock
     *
     * @param specialStock the value for xTend_MaterialTransactions.SpecialStock
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setSpecialStock(String specialStock) {
        this.specialStock = specialStock == null ? null : specialStock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.FromStockLocation
     *
     * @return the value of xTend_MaterialTransactions.FromStockLocation
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getFromStockLocation() {
        return fromStockLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.FromStockLocation
     *
     * @param fromStockLocation the value for xTend_MaterialTransactions.FromStockLocation
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setFromStockLocation(String fromStockLocation) {
        this.fromStockLocation = fromStockLocation == null ? null : fromStockLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.ToStockLocation
     *
     * @return the value of xTend_MaterialTransactions.ToStockLocation
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getToStockLocation() {
        return toStockLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.ToStockLocation
     *
     * @param toStockLocation the value for xTend_MaterialTransactions.ToStockLocation
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setToStockLocation(String toStockLocation) {
        this.toStockLocation = toStockLocation == null ? null : toStockLocation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.ERPFromStock
     *
     * @return the value of xTend_MaterialTransactions.ERPFromStock
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getERPFromStock() {
        return ERPFromStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.ERPFromStock
     *
     * @param ERPFromStock the value for xTend_MaterialTransactions.ERPFromStock
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setERPFromStock(String ERPFromStock) {
        this.ERPFromStock = ERPFromStock == null ? null : ERPFromStock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.ERPToStock
     *
     * @return the value of xTend_MaterialTransactions.ERPToStock
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getERPToStock() {
        return ERPToStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.ERPToStock
     *
     * @param ERPToStock the value for xTend_MaterialTransactions.ERPToStock
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setERPToStock(String ERPToStock) {
        this.ERPToStock = ERPToStock == null ? null : ERPToStock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.I_PRUEFLOS
     *
     * @return the value of xTend_MaterialTransactions.I_PRUEFLOS
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getI_PRUEFLOS() {
        return i_PRUEFLOS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.I_PRUEFLOS
     *
     * @param i_PRUEFLOS the value for xTend_MaterialTransactions.I_PRUEFLOS
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setI_PRUEFLOS(String i_PRUEFLOS) {
        this.i_PRUEFLOS = i_PRUEFLOS == null ? null : i_PRUEFLOS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.I_VCODE
     *
     * @return the value of xTend_MaterialTransactions.I_VCODE
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getI_VCODE() {
        return i_VCODE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.I_VCODE
     *
     * @param i_VCODE the value for xTend_MaterialTransactions.I_VCODE
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setI_VCODE(String i_VCODE) {
        this.i_VCODE = i_VCODE == null ? null : i_VCODE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.GR_RCPT
     *
     * @return the value of xTend_MaterialTransactions.GR_RCPT
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getGR_RCPT() {
        return GR_RCPT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.GR_RCPT
     *
     * @param GR_RCPT the value for xTend_MaterialTransactions.GR_RCPT
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setGR_RCPT(String GR_RCPT) {
        this.GR_RCPT = GR_RCPT == null ? null : GR_RCPT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.COSTCENTER
     *
     * @return the value of xTend_MaterialTransactions.COSTCENTER
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getCOSTCENTER() {
        return COSTCENTER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.COSTCENTER
     *
     * @param COSTCENTER the value for xTend_MaterialTransactions.COSTCENTER
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setCOSTCENTER(String COSTCENTER) {
        this.COSTCENTER = COSTCENTER == null ? null : COSTCENTER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.IND_PROPOSE_QUANX
     *
     * @return the value of xTend_MaterialTransactions.IND_PROPOSE_QUANX
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getIND_PROPOSE_QUANX() {
        return IND_PROPOSE_QUANX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.IND_PROPOSE_QUANX
     *
     * @param IND_PROPOSE_QUANX the value for xTend_MaterialTransactions.IND_PROPOSE_QUANX
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setIND_PROPOSE_QUANX(String IND_PROPOSE_QUANX) {
        this.IND_PROPOSE_QUANX = IND_PROPOSE_QUANX == null ? null : IND_PROPOSE_QUANX.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.MOVE_MAT
     *
     * @return the value of xTend_MaterialTransactions.MOVE_MAT
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getMOVE_MAT() {
        return MOVE_MAT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.MOVE_MAT
     *
     * @param MOVE_MAT the value for xTend_MaterialTransactions.MOVE_MAT
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setMOVE_MAT(String MOVE_MAT) {
        this.MOVE_MAT = MOVE_MAT == null ? null : MOVE_MAT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.MOVE_BATCH
     *
     * @return the value of xTend_MaterialTransactions.MOVE_BATCH
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getMOVE_BATCH() {
        return MOVE_BATCH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.MOVE_BATCH
     *
     * @param MOVE_BATCH the value for xTend_MaterialTransactions.MOVE_BATCH
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setMOVE_BATCH(String MOVE_BATCH) {
        this.MOVE_BATCH = MOVE_BATCH == null ? null : MOVE_BATCH.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.MOVE_PLANT
     *
     * @return the value of xTend_MaterialTransactions.MOVE_PLANT
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getMOVE_PLANT() {
        return MOVE_PLANT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.MOVE_PLANT
     *
     * @param MOVE_PLANT the value for xTend_MaterialTransactions.MOVE_PLANT
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setMOVE_PLANT(String MOVE_PLANT) {
        this.MOVE_PLANT = MOVE_PLANT == null ? null : MOVE_PLANT.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.PO_ITEM
     *
     * @return the value of xTend_MaterialTransactions.PO_ITEM
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getPO_ITEM() {
        return PO_ITEM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.PO_ITEM
     *
     * @param PO_ITEM the value for xTend_MaterialTransactions.PO_ITEM
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setPO_ITEM(String PO_ITEM) {
        this.PO_ITEM = PO_ITEM == null ? null : PO_ITEM.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.PO_NUMBER
     *
     * @return the value of xTend_MaterialTransactions.PO_NUMBER
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getPO_NUMBER() {
        return PO_NUMBER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.PO_NUMBER
     *
     * @param PO_NUMBER the value for xTend_MaterialTransactions.PO_NUMBER
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setPO_NUMBER(String PO_NUMBER) {
        this.PO_NUMBER = PO_NUMBER == null ? null : PO_NUMBER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.ORDERID
     *
     * @return the value of xTend_MaterialTransactions.ORDERID
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getORDERID() {
        return ORDERID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.ORDERID
     *
     * @param ORDERID the value for xTend_MaterialTransactions.ORDERID
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setORDERID(String ORDERID) {
        this.ORDERID = ORDERID == null ? null : ORDERID.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.ORDER_ITNO
     *
     * @return the value of xTend_MaterialTransactions.ORDER_ITNO
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getORDER_ITNO() {
        return ORDER_ITNO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.ORDER_ITNO
     *
     * @param ORDER_ITNO the value for xTend_MaterialTransactions.ORDER_ITNO
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setORDER_ITNO(String ORDER_ITNO) {
        this.ORDER_ITNO = ORDER_ITNO == null ? null : ORDER_ITNO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.REF_DOC
     *
     * @return the value of xTend_MaterialTransactions.REF_DOC
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getREF_DOC() {
        return REF_DOC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.REF_DOC
     *
     * @param REF_DOC the value for xTend_MaterialTransactions.REF_DOC
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setREF_DOC(String REF_DOC) {
        this.REF_DOC = REF_DOC == null ? null : REF_DOC.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.REF_DOC_YR
     *
     * @return the value of xTend_MaterialTransactions.REF_DOC_YR
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getREF_DOC_YR() {
        return REF_DOC_YR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.REF_DOC_YR
     *
     * @param REF_DOC_YR the value for xTend_MaterialTransactions.REF_DOC_YR
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setREF_DOC_YR(String REF_DOC_YR) {
        this.REF_DOC_YR = REF_DOC_YR == null ? null : REF_DOC_YR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.GRN
     *
     * @return the value of xTend_MaterialTransactions.GRN
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getGRN() {
        return GRN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.GRN
     *
     * @param GRN the value for xTend_MaterialTransactions.GRN
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setGRN(String GRN) {
        this.GRN = GRN == null ? null : GRN.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.TO_Name
     *
     * @return the value of xTend_MaterialTransactions.TO_Name
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getTO_Name() {
        return TO_Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.TO_Name
     *
     * @param TO_Name the value for xTend_MaterialTransactions.TO_Name
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setTO_Name(String TO_Name) {
        this.TO_Name = TO_Name == null ? null : TO_Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.Remarks_351
     *
     * @return the value of xTend_MaterialTransactions.Remarks_351
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getRemarks_351() {
        return remarks_351;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.Remarks_351
     *
     * @param remarks_351 the value for xTend_MaterialTransactions.Remarks_351
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setRemarks_351(String remarks_351) {
        this.remarks_351 = remarks_351 == null ? null : remarks_351.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.insert_311_option
     *
     * @return the value of xTend_MaterialTransactions.insert_311_option
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getInsert_311_option() {
        return insert_311_option;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.insert_311_option
     *
     * @param insert_311_option the value for xTend_MaterialTransactions.insert_311_option
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setInsert_311_option(String insert_311_option) {
        this.insert_311_option = insert_311_option == null ? null : insert_311_option.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.PO_TO_PO
     *
     * @return the value of xTend_MaterialTransactions.PO_TO_PO
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getPO_TO_PO() {
        return PO_TO_PO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.PO_TO_PO
     *
     * @param PO_TO_PO the value for xTend_MaterialTransactions.PO_TO_PO
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setPO_TO_PO(String PO_TO_PO) {
        this.PO_TO_PO = PO_TO_PO == null ? null : PO_TO_PO.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.Qty_261
     *
     * @return the value of xTend_MaterialTransactions.Qty_261
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public Double getQty_261() {
        return qty_261;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.Qty_261
     *
     * @param qty_261 the value for xTend_MaterialTransactions.Qty_261
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setQty_261(Double qty_261) {
        this.qty_261 = qty_261;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.SmartCar_Status
     *
     * @return the value of xTend_MaterialTransactions.SmartCar_Status
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getSmartCar_Status() {
        return smartCar_Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.SmartCar_Status
     *
     * @param smartCar_Status the value for xTend_MaterialTransactions.SmartCar_Status
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setSmartCar_Status(String smartCar_Status) {
        this.smartCar_Status = smartCar_Status == null ? null : smartCar_Status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xTend_MaterialTransactions.Car_No
     *
     * @return the value of xTend_MaterialTransactions.Car_No
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public String getCar_No() {
        return car_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xTend_MaterialTransactions.Car_No
     *
     * @param car_No the value for xTend_MaterialTransactions.Car_No
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    public void setCar_No(String car_No) {
        this.car_No = car_No == null ? null : car_No.trim();
    }
}