package com.ht.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.ht.entity.InventoryTakeDownEntity;
import com.ht.entity.InventoryTakeDownExample;

@Mapper
public interface InventoryTakeDownMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAInventoryTakeDown
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    int countByExample(InventoryTakeDownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAInventoryTakeDown
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    int deleteByExample(InventoryTakeDownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAInventoryTakeDown
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    int insert(InventoryTakeDownEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAInventoryTakeDown
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    int insertSelective(InventoryTakeDownEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAInventoryTakeDown
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    List<InventoryTakeDownEntity> selectByExample(InventoryTakeDownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAInventoryTakeDown
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    int updateByExampleSelective(@Param("record") InventoryTakeDownEntity record, @Param("example") InventoryTakeDownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAInventoryTakeDown
     *
     * @mbggenerated Mon Jul 18 14:52:27 CST 2022
     */
    int updateByExample(@Param("record") InventoryTakeDownEntity record, @Param("example") InventoryTakeDownExample example);
}