package com.ht.mapper;

import com.ht.entity.PCBAMI;
import com.ht.entity.PCBAMIExample;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface PCBAMIMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAMI
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    int countByExample(PCBAMIExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAMI
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    int deleteByExample(PCBAMIExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAMI
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    int insert(PCBAMI record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAMI
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    int insertSelective(PCBAMI record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAMI
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    List<PCBAMI> selectByExample(PCBAMIExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAMI
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    int updateByExampleSelective(@Param("record") PCBAMI record, @Param("example") PCBAMIExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAMI
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    int updateByExample(@Param("record") PCBAMI record, @Param("example") PCBAMIExample example);
}