package com.ht.mapper;

import com.ht.entity.PCBASMT;
import com.ht.entity.PCBASMTExample;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface PCBASMTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBASMT
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    int countByExample(PCBASMTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBASMT
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    int deleteByExample(PCBASMTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBASMT
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    int insert(PCBASMT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBASMT
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    int insertSelective(PCBASMT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBASMT
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    List<PCBASMT> selectByExample(PCBASMTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBASMT
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    int updateByExampleSelective(@Param("record") PCBASMT record, @Param("example") PCBASMTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBASMT
     *
     * @mbggenerated Wed Oct 12 15:35:47 CST 2022
     */
    int updateByExample(@Param("record") PCBASMT record, @Param("example") PCBASMTExample example);
}