package com.ht.mapper;

import com.ht.entity.PCBAInventoryEntity1;
import com.ht.entity.PCBAInventoryExample1;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PCBAInventoryMapper1 {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAInventory
     *
     * @mbggenerated Thu Jul 14 22:31:02 CST 2022
     */
    int countByExample(PCBAInventoryExample1 example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAInventory
     *
     * @mbggenerated Thu Jul 14 22:31:02 CST 2022
     */
    int deleteByExample(PCBAInventoryExample1 example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAInventory
     *
     * @mbggenerated Thu Jul 14 22:31:02 CST 2022
     */
    int insert(PCBAInventoryEntity1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAInventory
     *
     * @mbggenerated Thu Jul 14 22:31:02 CST 2022
     */
    int insertSelective(PCBAInventoryEntity1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAInventory
     *
     * @mbggenerated Thu Jul 14 22:31:02 CST 2022
     */
    List<PCBAInventoryEntity1> selectByExample(PCBAInventoryExample1 example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAInventory
     *
     * @mbggenerated Thu Jul 14 22:31:02 CST 2022
     */
    int updateByExampleSelective(@Param("record") PCBAInventoryEntity1 record, @Param("example") PCBAInventoryExample1 example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DL_PCBAInventory
     *
     * @mbggenerated Thu Jul 14 22:31:02 CST 2022
     */
    int updateByExample(@Param("record") PCBAInventoryEntity1 record, @Param("example") PCBAInventoryExample1 example);
}