package com.ht.mapper;

import com.ht.entity.Transaction;
import com.ht.entity.TransactionExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

/**
 * 过账表 mapper 接口
 *
 * @author 丁国钊
 */
@Mapper
@Repository
public interface TransactionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTransactions
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    int countByExample(TransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTransactions
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    int deleteByExample(TransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTransactions
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    int insert(Transaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTransactions
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    int insertSelective(Transaction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTransactions
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    List<Transaction> selectByExample(TransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTransactions
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    int updateByExampleSelective(@Param("record") Transaction record, @Param("example") TransactionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTransactions
     *
     * @mbggenerated Mon Dec 19 14:31:29 CST 2022
     */
    int updateByExample(@Param("record") Transaction record, @Param("example") TransactionExample example);
}