package com.ht.mapper;

import com.ht.entity.TransactionLog;
import com.ht.entity.TransactionLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TransactionLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTxnLog
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    int countByExample(TransactionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTxnLog
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    int deleteByExample(TransactionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTxnLog
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    int insert(TransactionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTxnLog
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    int insertSelective(TransactionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTxnLog
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    List<TransactionLog> selectByExample(TransactionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTxnLog
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    int updateByExampleSelective(@Param("record") TransactionLog record, @Param("example") TransactionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xTend_MaterialTxnLog
     *
     * @mbggenerated Mon Dec 19 14:31:30 CST 2022
     */
    int updateByExample(@Param("record") TransactionLog record, @Param("example") TransactionLogExample example);
}